//==========================================================================================================================
//Key is used to ensure the consistency of file version and content, and cannot be modified.
//Version Control is the version number written when the file is generated and cannot be modified.
//ToolMessage is used to record related information of any tool that has processed the file and cannot be manually modified.
//UserMessage is used by the user to write any information, which can be modified in any way.
//Content is the actual payload of the file.
//Parameter is the additional parameter information carried by the file and cannot be modified in any way.

//Key is generated by the hash of Version Control, Content and Parameter to ensure the consistency of the file.
//These three parts do not allow any individual modification
//==========================================================================================================================


//[UHDL]Key Start [md5:342c54c2a63975b81e8f5fbba3c02ee1]
//Version Control Hash: 3accddf64b1dd03abeb9b0b3e5a7ba44
//Content Hash: e6e29b1099a77bb51e6093771dc0d290
//Parameter Hash: d41d8cd98f00b204e9800998ecf8427e
//[UHDL]Key End [md5:342c54c2a63975b81e8f5fbba3c02ee1]

//[UHDL]Version Control Start [md5:3accddf64b1dd03abeb9b0b3e5a7ba44]
//[UHDL]Version Control Version:1.0.1
//[UHDL]Version Control End [md5:3accddf64b1dd03abeb9b0b3e5a7ba44]

//[UHDL]Tool Message Start [md5:3c89051661e5834d5ce7b281b64c76f9]
//Written by UHDL in 2022-10-14 13:28:18
//[UHDL]Tool Message End [md5:3c89051661e5834d5ce7b281b64c76f9]

//[UHDL]User Message Start [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]User Message End [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]Content Start [md5:e6e29b1099a77bb51e6093771dc0d290]
module VCompWrapper_ (
	input  [28:0] D_vcomp_din_signed_vec   ,
	output [31:0] D_vcomp_dout_signed_vec  ,
	input  [31:0] D_vcomp_din_unsigned_vec ,
	output [31:0] D_vcomp_dout_unsigned_vec,
	input         D_vcomp_din_unsigned     ,
	output        D_vcomp_dout_unsigned    ,
	input         D_vcomp_din_signed       ,
	output        D_vcomp_dout_signed      ,
	input         D_vcomp_din_reg          ,
	output        D_vcomp_dout_reg         );
	wire [28:0] vcomp_din_signed_vec   ;
	wire [31:0] vcomp_dout_signed_vec  ;
	wire [31:0] vcomp_din_unsigned_vec ;
	wire [31:0] vcomp_dout_unsigned_vec;
	wire        vcomp_din_unsigned     ;
	wire        vcomp_dout_unsigned    ;
	wire        vcomp_din_signed       ;
	wire        vcomp_dout_signed      ;
	wire        vcomp_din_reg          ;
	wire        vcomp_dout_reg         ;
	assign D_vcomp_dout_signed_vec = vcomp_dout_signed_vec;
	
	assign D_vcomp_dout_unsigned_vec = vcomp_dout_unsigned_vec;
	
	assign D_vcomp_dout_unsigned = vcomp_dout_unsigned;
	
	assign D_vcomp_dout_signed = vcomp_dout_signed;
	
	assign D_vcomp_dout_reg = vcomp_dout_reg;
	
	assign vcomp_din_signed_vec = D_vcomp_din_signed_vec;
	
	assign vcomp_din_unsigned_vec = D_vcomp_din_unsigned_vec;
	
	assign vcomp_din_unsigned = D_vcomp_din_unsigned;
	
	assign vcomp_din_signed = D_vcomp_din_signed;
	
	assign vcomp_din_reg = D_vcomp_din_reg;
	
	test vcomp #(
		.WIDTH(32),
		.DEPTH(13),
		.LOGIC(usr_type),
		.STR("asdf")
	)(
		.din_signed_vec(vcomp_din_signed_vec),
		.dout_signed_vec(vcomp_dout_signed_vec),
		.din_unsigned_vec(vcomp_din_unsigned_vec),
		.dout_unsigned_vec(vcomp_dout_unsigned_vec),
		.din_unsigned(vcomp_din_unsigned),
		.dout_unsigned(vcomp_dout_unsigned),
		.din_signed(vcomp_din_signed),
		.dout_signed(vcomp_dout_signed),
		.din_reg(vcomp_din_reg),
		.dout_reg(vcomp_dout_reg));

endmodule
//[UHDL]Content End [md5:e6e29b1099a77bb51e6093771dc0d290]

//[UHDL]Parameter Start [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]Parameter End [md5:d41d8cd98f00b204e9800998ecf8427e]

