//==========================================================================================================================
//Key is used to ensure the consistency of file version and content, and cannot be modified.
//Version Control is the version number written when the file is generated and cannot be modified.
//ToolMessage is used to record related information of any tool that has processed the file and cannot be manually modified.
//UserMessage is used by the user to write any information, which can be modified in any way.
//Content is the actual payload of the file.
//Parameter is the additional parameter information carried by the file and cannot be modified in any way.

//Key is generated by the hash of Version Control, Content and Parameter to ensure the consistency of the file.
//These three parts do not allow any individual modification
//==========================================================================================================================


//[UHDL]Key Start [md5:ef636ae61002e58ec52d133ea503599c]
//Version Control Hash: 3accddf64b1dd03abeb9b0b3e5a7ba44
//Content Hash: 9d0a633f2242c6ca0bd5b3b72acb5a8f
//Parameter Hash: d41d8cd98f00b204e9800998ecf8427e
//[UHDL]Key End [md5:ef636ae61002e58ec52d133ea503599c]

//[UHDL]Version Control Start [md5:3accddf64b1dd03abeb9b0b3e5a7ba44]
//[UHDL]Version Control Version:1.0.1
//[UHDL]Version Control End [md5:3accddf64b1dd03abeb9b0b3e5a7ba44]

//[UHDL]Tool Message Start [md5:d03a6bee689749cf96e88bd529d1e8c4]
//Written by UHDL in 2022-08-27 10:08:58
//[UHDL]Tool Message End [md5:d03a6bee689749cf96e88bd529d1e8c4]

//[UHDL]User Message Start [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]User Message End [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]Content Start [md5:9d0a633f2242c6ca0bd5b3b72acb5a8f]
module DDec_node_D0_pld_width_360_id_type_mst (
	output         out0_vld   ,
	output         out1_vld   ,
	input          out0_rdy   ,
	input          out1_rdy   ,
	output         out0_head  ,
	output         out1_head  ,
	output         out0_tail  ,
	output         out1_tail  ,
	output [359:0] out0_pld   ,
	output [359:0] out1_pld   ,
	output [3:0]   out0_mst_id,
	output [3:0]   out1_mst_id,
	output [3:0]   out0_slv_id,
	output [3:0]   out1_slv_id,
	input          in0_vld    ,
	output         in0_rdy    ,
	input          in0_head   ,
	input          in0_tail   ,
	input  [359:0] in0_pld    ,
	input  [3:0]   in0_mst_id ,
	input  [3:0]   in0_slv_id );
	wire [0:0] id_hit_p0_id1;
	wire [0:0] sel_bit0     ;
	wire [0:0] id_hit_p1_id2;
	wire [0:0] sel_bit1     ;
	assign out0_vld = (sel_bit0 && in0_vld);
	
	assign out1_vld = (sel_bit1 && in0_vld);
	
	assign out0_head = in0_head;
	
	assign out1_head = in0_head;
	
	assign out0_tail = in0_tail;
	
	assign out1_tail = in0_tail;
	
	assign out0_pld = in0_pld;
	
	assign out1_pld = in0_pld;
	
	assign out0_mst_id = in0_mst_id;
	
	assign out1_mst_id = in0_mst_id;
	
	assign out0_slv_id = in0_slv_id;
	
	assign out1_slv_id = in0_slv_id;
	
	assign in0_rdy = ((sel_bit0 && out0_rdy) || (sel_bit1 && out1_rdy));
	
	assign id_hit_p0_id1 = (in0_mst_id == 4'b1);
	
	assign sel_bit0 = id_hit_p0_id1;
	
	assign id_hit_p1_id2 = (in0_mst_id == 4'b10);
	
	assign sel_bit1 = id_hit_p1_id2;
	

endmodule
//[UHDL]Content End [md5:9d0a633f2242c6ca0bd5b3b72acb5a8f]

//[UHDL]Parameter Start [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]Parameter End [md5:d41d8cd98f00b204e9800998ecf8427e]

