//==========================================================================================================================
//Key is used to ensure the consistency of file version and content, and cannot be modified.
//Version Control is the version number written when the file is generated and cannot be modified.
//ToolMessage is used to record related information of any tool that has processed the file and cannot be manually modified.
//UserMessage is used by the user to write any information, which can be modified in any way.
//Content is the actual payload of the file.
//Parameter is the additional parameter information carried by the file and cannot be modified in any way.

//Key is generated by the hash of Version Control, Content and Parameter to ensure the consistency of the file.
//These three parts do not allow any individual modification
//==========================================================================================================================


//[UHDL]Key Start [md5:cdf701f5d440eca221a1bf47b1ec532e]
//Version Control Hash: 3accddf64b1dd03abeb9b0b3e5a7ba44
//Content Hash: 071e7758080926a1b14ebcc9abbfdbd1
//Parameter Hash: d41d8cd98f00b204e9800998ecf8427e
//[UHDL]Key End [md5:cdf701f5d440eca221a1bf47b1ec532e]

//[UHDL]Version Control Start [md5:3accddf64b1dd03abeb9b0b3e5a7ba44]
//[UHDL]Version Control Version:1.0.1
//[UHDL]Version Control End [md5:3accddf64b1dd03abeb9b0b3e5a7ba44]

//[UHDL]Tool Message Start [md5:82a2ff4f875eeb9da718503c35fda4b2]
//Written by UHDL in 2022-09-22 20:11:02
//[UHDL]Tool Message End [md5:82a2ff4f875eeb9da718503c35fda4b2]

//[UHDL]User Message Start [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]User Message End [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]Content Start [md5:071e7758080926a1b14ebcc9abbfdbd1]
module DDecDual_node_D0 (
	input         clk              ,
	input         rst_n            ,
	input         in0_w_req_vld    ,
	output        in0_w_req_rdy    ,
	input         in0_w_req_head   ,
	input         in0_w_req_tail   ,
	input  [99:0] in0_w_req_pld    ,
	input  [3:0]  in0_w_req_src_id ,
	input  [3:0]  in0_w_req_tgt_id ,
	input  [7:0]  in0_w_req_txn_id ,
	input         in0_r_req_vld    ,
	output        in0_r_req_rdy    ,
	input         in0_r_req_head   ,
	input         in0_r_req_tail   ,
	input  [63:0] in0_r_req_pld    ,
	input  [3:0]  in0_r_req_src_id ,
	input  [3:0]  in0_r_req_tgt_id ,
	input  [7:0]  in0_r_req_txn_id ,
	output        in0_w_ack_vld    ,
	input         in0_w_ack_rdy    ,
	output        in0_w_ack_head   ,
	output        in0_w_ack_tail   ,
	output [1:0]  in0_w_ack_pld    ,
	output [3:0]  in0_w_ack_src_id ,
	output [3:0]  in0_w_ack_tgt_id ,
	output [7:0]  in0_w_ack_txn_id ,
	output        in0_r_ack_vld    ,
	input         in0_r_ack_rdy    ,
	output        in0_r_ack_head   ,
	output        in0_r_ack_tail   ,
	output [34:0] in0_r_ack_pld    ,
	output [3:0]  in0_r_ack_src_id ,
	output [3:0]  in0_r_ack_tgt_id ,
	output [7:0]  in0_r_ack_txn_id ,
	output        out0_w_req_vld   ,
	input         out0_w_req_dy    ,
	output        out0_w_req_head  ,
	output        out0_w_req_tail  ,
	output [99:0] out0_w_req_pld   ,
	output [3:0]  out0_w_req_src_id,
	output [3:0]  out0_w_req_tgt_id,
	output [7:0]  out0_w_req_txn_id,
	output        out1_w_req_vld   ,
	input         out1_w_req_dy    ,
	output        out1_w_req_head  ,
	output        out1_w_req_tail  ,
	output [99:0] out1_w_req_pld   ,
	output [3:0]  out1_w_req_src_id,
	output [3:0]  out1_w_req_tgt_id,
	output [7:0]  out1_w_req_txn_id,
	output        out0_r_req_vld   ,
	input         out0_r_req_dy    ,
	output        out0_r_req_head  ,
	output        out0_r_req_tail  ,
	output [63:0] out0_r_req_pld   ,
	output [3:0]  out0_r_req_src_id,
	output [3:0]  out0_r_req_tgt_id,
	output [7:0]  out0_r_req_txn_id,
	output        out1_r_req_vld   ,
	input         out1_r_req_dy    ,
	output        out1_r_req_head  ,
	output        out1_r_req_tail  ,
	output [63:0] out1_r_req_pld   ,
	output [3:0]  out1_r_req_src_id,
	output [3:0]  out1_r_req_tgt_id,
	output [7:0]  out1_r_req_txn_id,
	input         out0_w_ack_vld   ,
	output        out0_w_ack_rdy   ,
	input         out0_w_ack_head  ,
	input         out0_w_ack_tail  ,
	input  [1:0]  out0_w_ack_pld   ,
	input  [3:0]  out0_w_ack_src_id,
	input  [3:0]  out0_w_ack_tgt_id,
	input  [7:0]  out0_w_ack_txn_id,
	input         out1_w_ack_vld   ,
	output        out1_w_ack_rdy   ,
	input         out1_w_ack_head  ,
	input         out1_w_ack_tail  ,
	input  [1:0]  out1_w_ack_pld   ,
	input  [3:0]  out1_w_ack_src_id,
	input  [3:0]  out1_w_ack_tgt_id,
	input  [7:0]  out1_w_ack_txn_id,
	input         out0_r_ack_vld   ,
	output        out0_r_ack_dy    ,
	input         out0_r_ack_head  ,
	input         out0_r_ack_tail  ,
	input  [34:0] out0_r_ack_pld   ,
	input  [3:0]  out0_r_ack_src_id,
	input  [3:0]  out0_r_ack_tgt_id,
	input  [7:0]  out0_r_ack_txn_id,
	input         out1_r_ack_vld   ,
	output        out1_r_ack_dy    ,
	input         out1_r_ack_head  ,
	input         out1_r_ack_tail  ,
	input  [34:0] out1_r_ack_pld   ,
	input  [3:0]  out1_r_ack_src_id,
	input  [3:0]  out1_r_ack_tgt_id,
	input  [7:0]  out1_r_ack_txn_id);
	wire        wdec_din_vld    ;
	wire        wdec_din_rdy    ;
	wire        wdec_din_head   ;
	wire        wdec_din_tail   ;
	wire [99:0] wdec_din_pld    ;
	wire [3:0]  wdec_din_src_id ;
	wire [3:0]  wdec_din_tgt_id ;
	wire [7:0]  wdec_din_txn_id ;
	wire        wdec_out0_vld   ;
	wire        wdec_out0_rdy   ;
	wire        wdec_out0_head  ;
	wire        wdec_out0_tail  ;
	wire [99:0] wdec_out0_pld   ;
	wire [3:0]  wdec_out0_src_id;
	wire [3:0]  wdec_out0_tgt_id;
	wire [7:0]  wdec_out0_txn_id;
	wire        wdec_out1_vld   ;
	wire        wdec_out1_rdy   ;
	wire        wdec_out1_head  ;
	wire        wdec_out1_tail  ;
	wire [99:0] wdec_out1_pld   ;
	wire [3:0]  wdec_out1_src_id;
	wire [3:0]  wdec_out1_tgt_id;
	wire [7:0]  wdec_out1_txn_id;
	wire        warb_clk        ;
	wire        warb_rst_n      ;
	wire        warb_out_vld    ;
	wire        warb_out_rdy    ;
	wire        warb_out_head   ;
	wire        warb_out_tail   ;
	wire [1:0]  warb_out_pld    ;
	wire [3:0]  warb_out_src_id ;
	wire [3:0]  warb_out_tgt_id ;
	wire [7:0]  warb_out_txn_id ;
	wire        warb_in0_vld    ;
	wire        warb_in0_rdy    ;
	wire        warb_in0_head   ;
	wire        warb_in0_ail    ;
	wire [1:0]  warb_in0_pld    ;
	wire [3:0]  warb_in0_src_id ;
	wire [3:0]  warb_in0_gt_id  ;
	wire [7:0]  warb_in0_xn_id  ;
	wire        warb_in1_vld    ;
	wire        warb_in1_rdy    ;
	wire        warb_in1_head   ;
	wire        warb_in1_ail    ;
	wire [1:0]  warb_in1_pld    ;
	wire [3:0]  warb_in1_src_id ;
	wire [3:0]  warb_in1_gt_id  ;
	wire [7:0]  warb_in1_xn_id  ;
	wire        rdec_din_vld    ;
	wire        rdec_din_rdy    ;
	wire        rdec_din_head   ;
	wire        rdec_din_tail   ;
	wire [63:0] rdec_din_pld    ;
	wire [3:0]  rdec_din_src_id ;
	wire [3:0]  rdec_din_tgt_id ;
	wire [7:0]  rdec_din_txn_id ;
	wire        rdec_out0_vld   ;
	wire        rdec_out0_rdy   ;
	wire        rdec_out0_head  ;
	wire        rdec_out0_tail  ;
	wire [63:0] rdec_out0_pld   ;
	wire [3:0]  rdec_out0_src_id;
	wire [3:0]  rdec_out0_tgt_id;
	wire [7:0]  rdec_out0_txn_id;
	wire        rdec_out1_vld   ;
	wire        rdec_out1_rdy   ;
	wire        rdec_out1_head  ;
	wire        rdec_out1_tail  ;
	wire [63:0] rdec_out1_pld   ;
	wire [3:0]  rdec_out1_src_id;
	wire [3:0]  rdec_out1_tgt_id;
	wire [7:0]  rdec_out1_txn_id;
	wire        rarb_clk        ;
	wire        rarb_rst_n      ;
	wire        rarb_out_vld    ;
	wire        rarb_out_rdy    ;
	wire        rarb_out_head   ;
	wire        rarb_out_tail   ;
	wire [34:0] rarb_out_pld    ;
	wire [3:0]  rarb_out_src_id ;
	wire [3:0]  rarb_out_tgt_id ;
	wire [7:0]  rarb_out_txn_id ;
	wire        rarb_in0_vld    ;
	wire        rarb_in0_rdy    ;
	wire        rarb_in0_head   ;
	wire        rarb_in0_ail    ;
	wire [34:0] rarb_in0_pld    ;
	wire [3:0]  rarb_in0_src_id ;
	wire [3:0]  rarb_in0_gt_id  ;
	wire [7:0]  rarb_in0_xn_id  ;
	wire        rarb_in1_vld    ;
	wire        rarb_in1_rdy    ;
	wire        rarb_in1_head   ;
	wire        rarb_in1_ail    ;
	wire [34:0] rarb_in1_pld    ;
	wire [3:0]  rarb_in1_src_id ;
	wire [3:0]  rarb_in1_gt_id  ;
	wire [7:0]  rarb_in1_xn_id  ;
	assign in0_w_req_rdy = wdec_din_rdy;
	
	assign in0_r_req_rdy = rdec_din_rdy;
	
	assign in0_w_ack_vld = warb_out_vld;
	
	assign in0_w_ack_head = warb_out_head;
	
	assign in0_w_ack_tail = warb_out_tail;
	
	assign in0_w_ack_pld = warb_out_pld;
	
	assign in0_w_ack_src_id = warb_out_src_id;
	
	assign in0_w_ack_tgt_id = warb_out_tgt_id;
	
	assign in0_w_ack_txn_id = warb_out_txn_id;
	
	assign in0_r_ack_vld = rarb_out_vld;
	
	assign in0_r_ack_head = rarb_out_head;
	
	assign in0_r_ack_tail = rarb_out_tail;
	
	assign in0_r_ack_pld = rarb_out_pld;
	
	assign in0_r_ack_src_id = rarb_out_src_id;
	
	assign in0_r_ack_tgt_id = rarb_out_tgt_id;
	
	assign in0_r_ack_txn_id = rarb_out_txn_id;
	
	assign out0_w_req_vld = wdec_out0_vld;
	
	assign out0_w_req_head = wdec_out0_head;
	
	assign out0_w_req_tail = wdec_out0_tail;
	
	assign out0_w_req_pld = wdec_out0_pld;
	
	assign out0_w_req_src_id = wdec_out0_src_id;
	
	assign out0_w_req_tgt_id = wdec_out0_tgt_id;
	
	assign out0_w_req_txn_id = wdec_out0_txn_id;
	
	assign out1_w_req_vld = wdec_out1_vld;
	
	assign out1_w_req_head = wdec_out1_head;
	
	assign out1_w_req_tail = wdec_out1_tail;
	
	assign out1_w_req_pld = wdec_out1_pld;
	
	assign out1_w_req_src_id = wdec_out1_src_id;
	
	assign out1_w_req_tgt_id = wdec_out1_tgt_id;
	
	assign out1_w_req_txn_id = wdec_out1_txn_id;
	
	assign out0_r_req_vld = rdec_out0_vld;
	
	assign out0_r_req_head = rdec_out0_head;
	
	assign out0_r_req_tail = rdec_out0_tail;
	
	assign out0_r_req_pld = rdec_out0_pld;
	
	assign out0_r_req_src_id = rdec_out0_src_id;
	
	assign out0_r_req_tgt_id = rdec_out0_tgt_id;
	
	assign out0_r_req_txn_id = rdec_out0_txn_id;
	
	assign out1_r_req_vld = rdec_out1_vld;
	
	assign out1_r_req_head = rdec_out1_head;
	
	assign out1_r_req_tail = rdec_out1_tail;
	
	assign out1_r_req_pld = rdec_out1_pld;
	
	assign out1_r_req_src_id = rdec_out1_src_id;
	
	assign out1_r_req_tgt_id = rdec_out1_tgt_id;
	
	assign out1_r_req_txn_id = rdec_out1_txn_id;
	
	assign out0_w_ack_rdy = warb_in0_rdy;
	
	assign out1_w_ack_rdy = warb_in1_rdy;
	
	assign out0_r_ack_dy = rarb_in0_rdy;
	
	assign out1_r_ack_dy = rarb_in1_rdy;
	
	assign wdec_din_vld = in0_w_req_vld;
	
	assign wdec_din_head = in0_w_req_head;
	
	assign wdec_din_tail = in0_w_req_tail;
	
	assign wdec_din_pld = in0_w_req_pld;
	
	assign wdec_din_src_id = in0_w_req_src_id;
	
	assign wdec_din_tgt_id = in0_w_req_tgt_id;
	
	assign wdec_din_txn_id = in0_w_req_txn_id;
	
	assign wdec_out0_rdy = out0_w_req_dy;
	
	assign wdec_out1_rdy = out1_w_req_dy;
	
	assign warb_clk = clk;
	
	assign warb_rst_n = rst_n;
	
	assign warb_out_rdy = in0_w_ack_rdy;
	
	assign warb_in0_vld = out0_w_ack_vld;
	
	assign warb_in0_head = out0_w_ack_head;
	
	assign warb_in0_ail = out0_w_ack_tail;
	
	assign warb_in0_pld = out0_w_ack_pld;
	
	assign warb_in0_src_id = out0_w_ack_src_id;
	
	assign warb_in0_gt_id = out0_w_ack_tgt_id;
	
	assign warb_in0_xn_id = out0_w_ack_txn_id;
	
	assign warb_in1_vld = out1_w_ack_vld;
	
	assign warb_in1_head = out1_w_ack_head;
	
	assign warb_in1_ail = out1_w_ack_tail;
	
	assign warb_in1_pld = out1_w_ack_pld;
	
	assign warb_in1_src_id = out1_w_ack_src_id;
	
	assign warb_in1_gt_id = out1_w_ack_tgt_id;
	
	assign warb_in1_xn_id = out1_w_ack_txn_id;
	
	assign rdec_din_vld = in0_r_req_vld;
	
	assign rdec_din_head = in0_r_req_head;
	
	assign rdec_din_tail = in0_r_req_tail;
	
	assign rdec_din_pld = in0_r_req_pld;
	
	assign rdec_din_src_id = in0_r_req_src_id;
	
	assign rdec_din_tgt_id = in0_r_req_tgt_id;
	
	assign rdec_din_txn_id = in0_r_req_txn_id;
	
	assign rdec_out0_rdy = out0_r_req_dy;
	
	assign rdec_out1_rdy = out1_r_req_dy;
	
	assign rarb_clk = clk;
	
	assign rarb_rst_n = rst_n;
	
	assign rarb_out_rdy = in0_r_ack_rdy;
	
	assign rarb_in0_vld = out0_r_ack_vld;
	
	assign rarb_in0_head = out0_r_ack_head;
	
	assign rarb_in0_ail = out0_r_ack_tail;
	
	assign rarb_in0_pld = out0_r_ack_pld;
	
	assign rarb_in0_src_id = out0_r_ack_src_id;
	
	assign rarb_in0_gt_id = out0_r_ack_tgt_id;
	
	assign rarb_in0_xn_id = out0_r_ack_txn_id;
	
	assign rarb_in1_vld = out1_r_ack_vld;
	
	assign rarb_in1_head = out1_r_ack_head;
	
	assign rarb_in1_ail = out1_r_ack_tail;
	
	assign rarb_in1_pld = out1_r_ack_pld;
	
	assign rarb_in1_src_id = out1_r_ack_src_id;
	
	assign rarb_in1_gt_id = out1_r_ack_tgt_id;
	
	assign rarb_in1_xn_id = out1_r_ack_txn_id;
	
	DDec_node_D0_pld_width_100_id_type_tgt wdec (
		.din_vld(wdec_din_vld),
		.din_rdy(wdec_din_rdy),
		.din_head(wdec_din_head),
		.din_tail(wdec_din_tail),
		.din_pld(wdec_din_pld),
		.din_src_id(wdec_din_src_id),
		.din_tgt_id(wdec_din_tgt_id),
		.din_txn_id(wdec_din_txn_id),
		.out0_vld(wdec_out0_vld),
		.out0_rdy(wdec_out0_rdy),
		.out0_head(wdec_out0_head),
		.out0_tail(wdec_out0_tail),
		.out0_pld(wdec_out0_pld),
		.out0_src_id(wdec_out0_src_id),
		.out0_tgt_id(wdec_out0_tgt_id),
		.out0_txn_id(wdec_out0_txn_id),
		.out1_vld(wdec_out1_vld),
		.out1_rdy(wdec_out1_rdy),
		.out1_head(wdec_out1_head),
		.out1_tail(wdec_out1_tail),
		.out1_pld(wdec_out1_pld),
		.out1_src_id(wdec_out1_src_id),
		.out1_tgt_id(wdec_out1_tgt_id),
		.out1_txn_id(wdec_out1_txn_id));
	DArb_node_D0_pld_width_2_id_type_tgt warb (
		.clk(warb_clk),
		.rst_n(warb_rst_n),
		.out_vld(warb_out_vld),
		.out_rdy(warb_out_rdy),
		.out_head(warb_out_head),
		.out_tail(warb_out_tail),
		.out_pld(warb_out_pld),
		.out_src_id(warb_out_src_id),
		.out_tgt_id(warb_out_tgt_id),
		.out_txn_id(warb_out_txn_id),
		.in0_vld(warb_in0_vld),
		.in0_rdy(warb_in0_rdy),
		.in0_head(warb_in0_head),
		.in0_ail(warb_in0_ail),
		.in0_pld(warb_in0_pld),
		.in0_src_id(warb_in0_src_id),
		.in0_gt_id(warb_in0_gt_id),
		.in0_xn_id(warb_in0_xn_id),
		.in1_vld(warb_in1_vld),
		.in1_rdy(warb_in1_rdy),
		.in1_head(warb_in1_head),
		.in1_ail(warb_in1_ail),
		.in1_pld(warb_in1_pld),
		.in1_src_id(warb_in1_src_id),
		.in1_gt_id(warb_in1_gt_id),
		.in1_xn_id(warb_in1_xn_id));
	DDec_node_D0_pld_width_64_id_type_tgt rdec (
		.din_vld(rdec_din_vld),
		.din_rdy(rdec_din_rdy),
		.din_head(rdec_din_head),
		.din_tail(rdec_din_tail),
		.din_pld(rdec_din_pld),
		.din_src_id(rdec_din_src_id),
		.din_tgt_id(rdec_din_tgt_id),
		.din_txn_id(rdec_din_txn_id),
		.out0_vld(rdec_out0_vld),
		.out0_rdy(rdec_out0_rdy),
		.out0_head(rdec_out0_head),
		.out0_tail(rdec_out0_tail),
		.out0_pld(rdec_out0_pld),
		.out0_src_id(rdec_out0_src_id),
		.out0_tgt_id(rdec_out0_tgt_id),
		.out0_txn_id(rdec_out0_txn_id),
		.out1_vld(rdec_out1_vld),
		.out1_rdy(rdec_out1_rdy),
		.out1_head(rdec_out1_head),
		.out1_tail(rdec_out1_tail),
		.out1_pld(rdec_out1_pld),
		.out1_src_id(rdec_out1_src_id),
		.out1_tgt_id(rdec_out1_tgt_id),
		.out1_txn_id(rdec_out1_txn_id));
	DArb_node_D0_pld_width_35_id_type_tgt rarb (
		.clk(rarb_clk),
		.rst_n(rarb_rst_n),
		.out_vld(rarb_out_vld),
		.out_rdy(rarb_out_rdy),
		.out_head(rarb_out_head),
		.out_tail(rarb_out_tail),
		.out_pld(rarb_out_pld),
		.out_src_id(rarb_out_src_id),
		.out_tgt_id(rarb_out_tgt_id),
		.out_txn_id(rarb_out_txn_id),
		.in0_vld(rarb_in0_vld),
		.in0_rdy(rarb_in0_rdy),
		.in0_head(rarb_in0_head),
		.in0_ail(rarb_in0_ail),
		.in0_pld(rarb_in0_pld),
		.in0_src_id(rarb_in0_src_id),
		.in0_gt_id(rarb_in0_gt_id),
		.in0_xn_id(rarb_in0_xn_id),
		.in1_vld(rarb_in1_vld),
		.in1_rdy(rarb_in1_rdy),
		.in1_head(rarb_in1_head),
		.in1_ail(rarb_in1_ail),
		.in1_pld(rarb_in1_pld),
		.in1_src_id(rarb_in1_src_id),
		.in1_gt_id(rarb_in1_gt_id),
		.in1_xn_id(rarb_in1_xn_id));

endmodule
//[UHDL]Content End [md5:071e7758080926a1b14ebcc9abbfdbd1]

//[UHDL]Parameter Start [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]Parameter End [md5:d41d8cd98f00b204e9800998ecf8427e]

