//==========================================================================================================================
//Key is used to ensure the consistency of file version and content, and cannot be modified.
//Version Control is the version number written when the file is generated and cannot be modified.
//ToolMessage is used to record related information of any tool that has processed the file and cannot be manually modified.
//UserMessage is used by the user to write any information, which can be modified in any way.
//Content is the actual payload of the file.
//Parameter is the additional parameter information carried by the file and cannot be modified in any way.

//Key is generated by the hash of Version Control, Content and Parameter to ensure the consistency of the file.
//These three parts do not allow any individual modification
//==========================================================================================================================


//[UHDL]Key Start [md5:ba33c2c37a6b702387687c27fe6db3df]
//Version Control Hash: 3accddf64b1dd03abeb9b0b3e5a7ba44
//Content Hash: ef01484279f2f7d10a68522ded14fe4c
//Parameter Hash: d41d8cd98f00b204e9800998ecf8427e
//[UHDL]Key End [md5:ba33c2c37a6b702387687c27fe6db3df]

//[UHDL]Version Control Start [md5:3accddf64b1dd03abeb9b0b3e5a7ba44]
//[UHDL]Version Control Version:1.0.1
//[UHDL]Version Control End [md5:3accddf64b1dd03abeb9b0b3e5a7ba44]

//[UHDL]Tool Message Start [md5:cda437c32f04161dc20423f9c5e5b253]
//Written by UHDL in 2022-08-11 22:09:42
//[UHDL]Tool Message End [md5:cda437c32f04161dc20423f9c5e5b253]

//[UHDL]User Message Start [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]User Message End [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]Content Start [md5:ef01484279f2f7d10a68522ded14fe4c]
module DSlv_node_S0 (
	input         in0_vld  ,
	output        in0_rdy  ,
	input         in0_head ,
	input         in0_tail ,
	input  [31:0] in0_pld  ,
	input  [2:0]  in0_id   ,
	output        out0_vld ,
	input         out0_rdy ,
	output        out0_head,
	output        out0_tail,
	output [31:0] out0_pld ,
	output [2:0]  out0_id  );
	assign in0_rdy = out0_rdy;
	
	assign out0_vld = in0_vld;
	
	assign out0_pld = in0_pld;
	
	assign out0_id = in0_id;
	

endmodule
//[UHDL]Content End [md5:ef01484279f2f7d10a68522ded14fe4c]

//[UHDL]Parameter Start [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]Parameter End [md5:d41d8cd98f00b204e9800998ecf8427e]

