//==========================================================================================================================
//Key is used to ensure the consistency of file version and content, and cannot be modified.
//Version Control is the version number written when the file is generated and cannot be modified.
//ToolMessage is used to record related information of any tool that has processed the file and cannot be manually modified.
//UserMessage is used by the user to write any information, which can be modified in any way.
//Content is the actual payload of the file.
//Parameter is the additional parameter information carried by the file and cannot be modified in any way.

//Key is generated by the hash of Version Control, Content and Parameter to ensure the consistency of the file.
//These three parts do not allow any individual modification
//==========================================================================================================================


//[UHDL]Key Start [md5:2288348a6bd12dca4e4e437137933c10]
//Version Control Hash: 3accddf64b1dd03abeb9b0b3e5a7ba44
//Content Hash: 1ab29aeac5f1b956084fd4c3681662ca
//Parameter Hash: d41d8cd98f00b204e9800998ecf8427e
//[UHDL]Key End [md5:2288348a6bd12dca4e4e437137933c10]

//[UHDL]Version Control Start [md5:3accddf64b1dd03abeb9b0b3e5a7ba44]
//[UHDL]Version Control Version:1.0.1
//[UHDL]Version Control End [md5:3accddf64b1dd03abeb9b0b3e5a7ba44]

//[UHDL]Tool Message Start [md5:d03a6bee689749cf96e88bd529d1e8c4]
//Written by UHDL in 2022-08-27 10:08:58
//[UHDL]Tool Message End [md5:d03a6bee689749cf96e88bd529d1e8c4]

//[UHDL]User Message Start [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]User Message End [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]Content Start [md5:1ab29aeac5f1b956084fd4c3681662ca]
module DWrap_network_network0 (
	input          clk             ,
	input          rst_n           ,
	input          D_S0_in_aw_vld  ,
	output         D_S0_in_aw_rdy  ,
	input  [31:0]  D_S0_in_aw_addr ,
	input  [7:0]   D_S0_in_aw_id   ,
	input  [31:0]  D_S0_in_aw_user ,
	input          D_S0_in_w_vld   ,
	output         D_S0_in_w_rdy   ,
	input          D_S0_in_w_last  ,
	input  [31:0]  D_S0_in_w_strb  ,
	input  [255:0] D_S0_in_w_data  ,
	output         D_S0_in_b_vld   ,
	input          D_S0_in_b_rdy   ,
	output [7:0]   D_S0_in_b_id    ,
	output [1:0]   D_S0_in_b_resp  ,
	input          D_S1_in_aw_vld  ,
	output         D_S1_in_aw_rdy  ,
	input  [31:0]  D_S1_in_aw_addr ,
	input  [7:0]   D_S1_in_aw_id   ,
	input  [31:0]  D_S1_in_aw_user ,
	input          D_S1_in_w_vld   ,
	output         D_S1_in_w_rdy   ,
	input          D_S1_in_w_last  ,
	input  [31:0]  D_S1_in_w_strb  ,
	input  [255:0] D_S1_in_w_data  ,
	output         D_S1_in_b_vld   ,
	input          D_S1_in_b_rdy   ,
	output [7:0]   D_S1_in_b_id    ,
	output [1:0]   D_S1_in_b_resp  ,
	output         D_M0_out_aw_vld ,
	input          D_M0_out_aw_rdy ,
	output [31:0]  D_M0_out_aw_addr,
	output [11:0]  D_M0_out_aw_id  ,
	output [31:0]  D_M0_out_aw_user,
	output         D_M0_out_w_vld  ,
	input          D_M0_out_w_rdy  ,
	output         D_M0_out_w_last ,
	output [31:0]  D_M0_out_w_strb ,
	output [255:0] D_M0_out_w_data ,
	input          D_M0_out_b_vld  ,
	output         D_M0_out_b_rdy  ,
	input  [11:0]  D_M0_out_b_id   ,
	input  [1:0]   D_M0_out_b_resp ,
	output         D_M0_out_ar_vld ,
	input          D_M0_out_ar_rdy ,
	output [31:0]  D_M0_out_ar_addr,
	output [11:0]  D_M0_out_ar_id  ,
	output [31:0]  D_M0_out_ar_user,
	input          D_M0_out_r_vld  ,
	output         D_M0_out_r_rdy  ,
	input  [11:0]  D_M0_out_r_id   ,
	input  [255:0] D_M0_out_r_data ,
	input  [1:0]   D_M0_out_r_resp ,
	input          D_M0_out_r_last ,
	output         D_M1_out_aw_vld ,
	input          D_M1_out_aw_rdy ,
	output [31:0]  D_M1_out_aw_addr,
	output [11:0]  D_M1_out_aw_id  ,
	output [31:0]  D_M1_out_aw_user,
	output         D_M1_out_w_vld  ,
	input          D_M1_out_w_rdy  ,
	output         D_M1_out_w_last ,
	output [31:0]  D_M1_out_w_strb ,
	output [255:0] D_M1_out_w_data ,
	input          D_M1_out_b_vld  ,
	output         D_M1_out_b_rdy  ,
	input  [11:0]  D_M1_out_b_id   ,
	input  [1:0]   D_M1_out_b_resp ,
	output         D_M1_out_ar_vld ,
	input          D_M1_out_ar_rdy ,
	output [31:0]  D_M1_out_ar_addr,
	output [11:0]  D_M1_out_ar_id  ,
	output [31:0]  D_M1_out_ar_user,
	input          D_M1_out_r_vld  ,
	output         D_M1_out_r_rdy  ,
	input  [11:0]  D_M1_out_r_id   ,
	input  [255:0] D_M1_out_r_data ,
	input  [1:0]   D_M1_out_r_resp ,
	input          D_M1_out_r_last );
	wire         S0_clk             ;
	wire         S0_rst_n           ;
	wire         S0_in_aw_vld       ;
	wire         S0_in_aw_rdy       ;
	wire [31:0]  S0_in_aw_addr      ;
	wire [7:0]   S0_in_aw_id        ;
	wire [31:0]  S0_in_aw_user      ;
	wire         S0_in_w_vld        ;
	wire         S0_in_w_rdy        ;
	wire         S0_in_w_last       ;
	wire [31:0]  S0_in_w_strb       ;
	wire [255:0] S0_in_w_data       ;
	wire         S0_in_b_vld        ;
	wire         S0_in_b_rdy        ;
	wire [7:0]   S0_in_b_id         ;
	wire [1:0]   S0_in_b_resp       ;
	wire         S0_out0_req_vld    ;
	wire         S0_out0_req_rdy    ;
	wire         S0_out0_req_head   ;
	wire         S0_out0_req_tail   ;
	wire [359:0] S0_out0_req_pld    ;
	wire [3:0]   S0_out0_req_mst_id ;
	wire [3:0]   S0_out0_req_slv_id ;
	wire         S0_out0_ack_vld    ;
	wire         S0_out0_ack_rdy    ;
	wire         S0_out0_ack_head   ;
	wire         S0_out0_ack_tail   ;
	wire [9:0]   S0_out0_ack_pld    ;
	wire [3:0]   S0_out0_ack_mst_id ;
	wire [3:0]   S0_out0_ack_slv_id ;
	wire         S1_clk             ;
	wire         S1_rst_n           ;
	wire         S1_in_aw_vld       ;
	wire         S1_in_aw_rdy       ;
	wire [31:0]  S1_in_aw_addr      ;
	wire [7:0]   S1_in_aw_id        ;
	wire [31:0]  S1_in_aw_user      ;
	wire         S1_in_w_vld        ;
	wire         S1_in_w_rdy        ;
	wire         S1_in_w_last       ;
	wire [31:0]  S1_in_w_strb       ;
	wire [255:0] S1_in_w_data       ;
	wire         S1_in_b_vld        ;
	wire         S1_in_b_rdy        ;
	wire [7:0]   S1_in_b_id         ;
	wire [1:0]   S1_in_b_resp       ;
	wire         S1_out0_req_vld    ;
	wire         S1_out0_req_rdy    ;
	wire         S1_out0_req_head   ;
	wire         S1_out0_req_tail   ;
	wire [359:0] S1_out0_req_pld    ;
	wire [3:0]   S1_out0_req_mst_id ;
	wire [3:0]   S1_out0_req_slv_id ;
	wire         S1_out0_ack_vld    ;
	wire         S1_out0_ack_rdy    ;
	wire         S1_out0_ack_head   ;
	wire         S1_out0_ack_tail   ;
	wire [9:0]   S1_out0_ack_pld    ;
	wire [3:0]   S1_out0_ack_mst_id ;
	wire [3:0]   S1_out0_ack_slv_id ;
	wire         A0_clk             ;
	wire         A0_rst_n           ;
	wire         A0_in0_req_vld     ;
	wire         A0_in1_req_vld     ;
	wire         A0_in0_req_rdy     ;
	wire         A0_in1_req_rdy     ;
	wire         A0_in0_req_head    ;
	wire         A0_in1_req_head    ;
	wire         A0_in0_req_tail    ;
	wire         A0_in1_req_tail    ;
	wire [359:0] A0_in0_req_pld     ;
	wire [359:0] A0_in1_req_pld     ;
	wire [3:0]   A0_in0_req_mst_id  ;
	wire [3:0]   A0_in1_req_mst_id  ;
	wire [3:0]   A0_in0_req_slv_id  ;
	wire [3:0]   A0_in1_req_slv_id  ;
	wire         A0_in0_ack_vld     ;
	wire         A0_in1_ack_vld     ;
	wire         A0_in0_ack_rdy     ;
	wire         A0_in1_ack_rdy     ;
	wire         A0_in0_ack_head    ;
	wire         A0_in1_ack_head    ;
	wire         A0_in0_ack_tail    ;
	wire         A0_in1_ack_tail    ;
	wire [9:0]   A0_in0_ack_pld     ;
	wire [9:0]   A0_in1_ack_pld     ;
	wire [3:0]   A0_in0_ack_mst_id  ;
	wire [3:0]   A0_in1_ack_mst_id  ;
	wire [3:0]   A0_in0_ack_slv_id  ;
	wire [3:0]   A0_in1_ack_slv_id  ;
	wire         A0_out0_req_vld    ;
	wire         A0_out0_req_rdy    ;
	wire         A0_out0_req_head   ;
	wire         A0_out0_req_tail   ;
	wire [359:0] A0_out0_req_pld    ;
	wire [3:0]   A0_out0_req_mst_id ;
	wire [3:0]   A0_out0_req_slv_id ;
	wire         A0_out0_ack_vld    ;
	wire         A0_out0_ack_rdy    ;
	wire         A0_out0_ack_head   ;
	wire         A0_out0_ack_tail   ;
	wire [9:0]   A0_out0_ack_pld    ;
	wire [3:0]   A0_out0_ack_mst_id ;
	wire [3:0]   A0_out0_ack_slv_id ;
	wire         D0_clk             ;
	wire         D0_rst_n           ;
	wire         D0_out0_req_vld    ;
	wire         D0_out1_req_vld    ;
	wire         D0_out0_req_rdy    ;
	wire         D0_out1_req_rdy    ;
	wire         D0_out0_req_head   ;
	wire         D0_out1_req_head   ;
	wire         D0_out0_req_tail   ;
	wire         D0_out1_req_tail   ;
	wire [359:0] D0_out0_req_pld    ;
	wire [359:0] D0_out1_req_pld    ;
	wire [3:0]   D0_out0_req_mst_id ;
	wire [3:0]   D0_out1_req_mst_id ;
	wire [3:0]   D0_out0_req_slv_id ;
	wire [3:0]   D0_out1_req_slv_id ;
	wire         D0_out0_ack_vld    ;
	wire         D0_out1_ack_vld    ;
	wire         D0_out0_ack_rdy    ;
	wire         D0_out1_ack_rdy    ;
	wire         D0_out0_ack_head   ;
	wire         D0_out1_ack_head   ;
	wire         D0_out0_ack_tail   ;
	wire         D0_out1_ack_tail   ;
	wire [9:0]   D0_out0_ack_pld    ;
	wire [9:0]   D0_out1_ack_pld    ;
	wire [3:0]   D0_out0_ack_mst_id ;
	wire [3:0]   D0_out1_ack_mst_id ;
	wire [3:0]   D0_out0_ack_slv_id ;
	wire [3:0]   D0_out1_ack_slv_id ;
	wire         D0_in0_req_vld     ;
	wire         D0_in0_req_rdy     ;
	wire         D0_in0_req_head    ;
	wire         D0_in0_req_tail    ;
	wire [359:0] D0_in0_req_pld     ;
	wire [3:0]   D0_in0_req_mst_id  ;
	wire [3:0]   D0_in0_req_slv_id  ;
	wire         D0_in0_ack_vld     ;
	wire         D0_in0_ack_rdy     ;
	wire         D0_in0_ack_head    ;
	wire         D0_in0_ack_tail    ;
	wire [9:0]   D0_in0_ack_pld     ;
	wire [3:0]   D0_in0_ack_mst_id  ;
	wire [3:0]   D0_in0_ack_slv_id  ;
	wire         M0_clk             ;
	wire         M0_rst_n           ;
	wire         M0_out_aw_vld      ;
	wire         M0_out_aw_rdy      ;
	wire [31:0]  M0_out_aw_addr     ;
	wire [11:0]  M0_out_aw_id       ;
	wire [31:0]  M0_out_aw_user     ;
	wire         M0_out_w_vld       ;
	wire         M0_out_w_rdy       ;
	wire         M0_out_w_last      ;
	wire [31:0]  M0_out_w_strb      ;
	wire [255:0] M0_out_w_data      ;
	wire         M0_out_b_vld       ;
	wire         M0_out_b_rdy       ;
	wire [11:0]  M0_out_b_id        ;
	wire [1:0]   M0_out_b_resp      ;
	wire         M0_in0_req_vld     ;
	wire         M0_in0_req_rdy     ;
	wire         M0_in0_req_head    ;
	wire         M0_in0_req_tail    ;
	wire [359:0] M0_in0_req_pld     ;
	wire [3:0]   M0_in0_req_mst_id  ;
	wire [3:0]   M0_in0_req_slv_id  ;
	wire         M0_in0_ack_vld     ;
	wire         M0_in0_ack_rdy     ;
	wire         M0_in0_ack_head    ;
	wire         M0_in0_ack_tail    ;
	wire [9:0]   M0_in0_ack_pld     ;
	wire [3:0]   M0_in0_ack_mst_id  ;
	wire [3:0]   M0_in0_ack_slv_id  ;
	wire         M0_out_ar_vld      ;
	wire         M0_out_ar_rdy      ;
	wire [31:0]  M0_out_ar_addr     ;
	wire [11:0]  M0_out_ar_id       ;
	wire [31:0]  M0_out_ar_user     ;
	wire         M0_out_r_vld       ;
	wire         M0_out_r_rdy       ;
	wire [11:0]  M0_out_r_id        ;
	wire [255:0] M0_out_r_data      ;
	wire [1:0]   M0_out_r_resp      ;
	wire         M0_out_r_last      ;
	wire         M0_in0_r_req_vld   ;
	wire         M0_in0_r_req_rdy   ;
	wire         M0_in0_r_req_head  ;
	wire         M0_in0_r_req_tail  ;
	wire [71:0]  M0_in0_r_req_pld   ;
	wire [3:0]   M0_in0_r_req_mst_id;
	wire [3:0]   M0_in0_r_req_slv_id;
	wire         M0_in0_r_ack_vld   ;
	wire         M0_in0_r_ack_rdy   ;
	wire         M0_in0_r_ack_head  ;
	wire         M0_in0_r_ack_tail  ;
	wire [265:0] M0_in0_r_ack_pld   ;
	wire [3:0]   M0_in0_r_ack_mst_id;
	wire [3:0]   M0_in0_r_ack_slv_id;
	wire         M1_clk             ;
	wire         M1_rst_n           ;
	wire         M1_out_aw_vld      ;
	wire         M1_out_aw_rdy      ;
	wire [31:0]  M1_out_aw_addr     ;
	wire [11:0]  M1_out_aw_id       ;
	wire [31:0]  M1_out_aw_user     ;
	wire         M1_out_w_vld       ;
	wire         M1_out_w_rdy       ;
	wire         M1_out_w_last      ;
	wire [31:0]  M1_out_w_strb      ;
	wire [255:0] M1_out_w_data      ;
	wire         M1_out_b_vld       ;
	wire         M1_out_b_rdy       ;
	wire [11:0]  M1_out_b_id        ;
	wire [1:0]   M1_out_b_resp      ;
	wire         M1_in0_req_vld     ;
	wire         M1_in0_req_rdy     ;
	wire         M1_in0_req_head    ;
	wire         M1_in0_req_tail    ;
	wire [359:0] M1_in0_req_pld     ;
	wire [3:0]   M1_in0_req_mst_id  ;
	wire [3:0]   M1_in0_req_slv_id  ;
	wire         M1_in0_ack_vld     ;
	wire         M1_in0_ack_rdy     ;
	wire         M1_in0_ack_head    ;
	wire         M1_in0_ack_tail    ;
	wire [9:0]   M1_in0_ack_pld     ;
	wire [3:0]   M1_in0_ack_mst_id  ;
	wire [3:0]   M1_in0_ack_slv_id  ;
	wire         M1_out_ar_vld      ;
	wire         M1_out_ar_rdy      ;
	wire [31:0]  M1_out_ar_addr     ;
	wire [11:0]  M1_out_ar_id       ;
	wire [31:0]  M1_out_ar_user     ;
	wire         M1_out_r_vld       ;
	wire         M1_out_r_rdy       ;
	wire [11:0]  M1_out_r_id        ;
	wire [255:0] M1_out_r_data      ;
	wire [1:0]   M1_out_r_resp      ;
	wire         M1_out_r_last      ;
	wire         M1_in0_r_req_vld   ;
	wire         M1_in0_r_req_rdy   ;
	wire         M1_in0_r_req_head  ;
	wire         M1_in0_r_req_tail  ;
	wire [71:0]  M1_in0_r_req_pld   ;
	wire [3:0]   M1_in0_r_req_mst_id;
	wire [3:0]   M1_in0_r_req_slv_id;
	wire         M1_in0_r_ack_vld   ;
	wire         M1_in0_r_ack_rdy   ;
	wire         M1_in0_r_ack_head  ;
	wire         M1_in0_r_ack_tail  ;
	wire [265:0] M1_in0_r_ack_pld   ;
	wire [3:0]   M1_in0_r_ack_mst_id;
	wire [3:0]   M1_in0_r_ack_slv_id;
	assign D_S0_in_aw_rdy = S0_in_aw_rdy;
	
	assign D_S0_in_w_rdy = S0_in_w_rdy;
	
	assign D_S0_in_b_vld = S0_in_b_vld;
	
	assign D_S0_in_b_id = S0_in_b_id;
	
	assign D_S0_in_b_resp = S0_in_b_resp;
	
	assign D_S1_in_aw_rdy = S1_in_aw_rdy;
	
	assign D_S1_in_w_rdy = S1_in_w_rdy;
	
	assign D_S1_in_b_vld = S1_in_b_vld;
	
	assign D_S1_in_b_id = S1_in_b_id;
	
	assign D_S1_in_b_resp = S1_in_b_resp;
	
	assign D_M0_out_aw_vld = M0_out_aw_vld;
	
	assign D_M0_out_aw_addr = M0_out_aw_addr;
	
	assign D_M0_out_aw_id = M0_out_aw_id;
	
	assign D_M0_out_aw_user = M0_out_aw_user;
	
	assign D_M0_out_w_vld = M0_out_w_vld;
	
	assign D_M0_out_w_last = M0_out_w_last;
	
	assign D_M0_out_w_strb = M0_out_w_strb;
	
	assign D_M0_out_w_data = M0_out_w_data;
	
	assign D_M0_out_b_rdy = M0_out_b_rdy;
	
	assign D_M0_out_ar_vld = M0_out_ar_vld;
	
	assign D_M0_out_ar_addr = M0_out_ar_addr;
	
	assign D_M0_out_ar_id = M0_out_ar_id;
	
	assign D_M0_out_ar_user = M0_out_ar_user;
	
	assign D_M0_out_r_rdy = M0_out_r_rdy;
	
	assign D_M1_out_aw_vld = M1_out_aw_vld;
	
	assign D_M1_out_aw_addr = M1_out_aw_addr;
	
	assign D_M1_out_aw_id = M1_out_aw_id;
	
	assign D_M1_out_aw_user = M1_out_aw_user;
	
	assign D_M1_out_w_vld = M1_out_w_vld;
	
	assign D_M1_out_w_last = M1_out_w_last;
	
	assign D_M1_out_w_strb = M1_out_w_strb;
	
	assign D_M1_out_w_data = M1_out_w_data;
	
	assign D_M1_out_b_rdy = M1_out_b_rdy;
	
	assign D_M1_out_ar_vld = M1_out_ar_vld;
	
	assign D_M1_out_ar_addr = M1_out_ar_addr;
	
	assign D_M1_out_ar_id = M1_out_ar_id;
	
	assign D_M1_out_ar_user = M1_out_ar_user;
	
	assign D_M1_out_r_rdy = M1_out_r_rdy;
	
	assign S0_clk = clk;
	
	assign S0_rst_n = rst_n;
	
	assign S0_in_aw_vld = D_S0_in_aw_vld;
	
	assign S0_in_aw_addr = D_S0_in_aw_addr;
	
	assign S0_in_aw_id = D_S0_in_aw_id;
	
	assign S0_in_aw_user = D_S0_in_aw_user;
	
	assign S0_in_w_vld = D_S0_in_w_vld;
	
	assign S0_in_w_last = D_S0_in_w_last;
	
	assign S0_in_w_strb = D_S0_in_w_strb;
	
	assign S0_in_w_data = D_S0_in_w_data;
	
	assign S0_in_b_rdy = D_S0_in_b_rdy;
	
	assign S0_out0_req_rdy = A0_in0_req_rdy;
	
	assign S0_out0_ack_vld = A0_in0_ack_vld;
	
	assign S0_out0_ack_head = A0_in0_ack_head;
	
	assign S0_out0_ack_tail = A0_in0_ack_tail;
	
	assign S0_out0_ack_pld = A0_in0_ack_pld;
	
	assign S0_out0_ack_mst_id = A0_in0_ack_mst_id;
	
	assign S0_out0_ack_slv_id = A0_in0_ack_slv_id;
	
	assign S1_clk = clk;
	
	assign S1_rst_n = rst_n;
	
	assign S1_in_aw_vld = D_S1_in_aw_vld;
	
	assign S1_in_aw_addr = D_S1_in_aw_addr;
	
	assign S1_in_aw_id = D_S1_in_aw_id;
	
	assign S1_in_aw_user = D_S1_in_aw_user;
	
	assign S1_in_w_vld = D_S1_in_w_vld;
	
	assign S1_in_w_last = D_S1_in_w_last;
	
	assign S1_in_w_strb = D_S1_in_w_strb;
	
	assign S1_in_w_data = D_S1_in_w_data;
	
	assign S1_in_b_rdy = D_S1_in_b_rdy;
	
	assign S1_out0_req_rdy = A0_in1_req_rdy;
	
	assign S1_out0_ack_vld = A0_in1_ack_vld;
	
	assign S1_out0_ack_head = A0_in1_ack_head;
	
	assign S1_out0_ack_tail = A0_in1_ack_tail;
	
	assign S1_out0_ack_pld = A0_in1_ack_pld;
	
	assign S1_out0_ack_mst_id = A0_in1_ack_mst_id;
	
	assign S1_out0_ack_slv_id = A0_in1_ack_slv_id;
	
	assign A0_clk = clk;
	
	assign A0_rst_n = rst_n;
	
	assign A0_in0_req_vld = S0_out0_req_vld;
	
	assign A0_in1_req_vld = S1_out0_req_vld;
	
	assign A0_in0_req_head = S0_out0_req_head;
	
	assign A0_in1_req_head = S1_out0_req_head;
	
	assign A0_in0_req_tail = S0_out0_req_tail;
	
	assign A0_in1_req_tail = S1_out0_req_tail;
	
	assign A0_in0_req_pld = S0_out0_req_pld;
	
	assign A0_in1_req_pld = S1_out0_req_pld;
	
	assign A0_in0_req_mst_id = S0_out0_req_mst_id;
	
	assign A0_in1_req_mst_id = S1_out0_req_mst_id;
	
	assign A0_in0_req_slv_id = S0_out0_req_slv_id;
	
	assign A0_in1_req_slv_id = S1_out0_req_slv_id;
	
	assign A0_in0_ack_rdy = S0_out0_ack_rdy;
	
	assign A0_in1_ack_rdy = S1_out0_ack_rdy;
	
	assign A0_out0_req_rdy = D0_in0_req_rdy;
	
	assign A0_out0_ack_vld = D0_in0_ack_vld;
	
	assign A0_out0_ack_head = D0_in0_ack_head;
	
	assign A0_out0_ack_tail = D0_in0_ack_tail;
	
	assign A0_out0_ack_pld = D0_in0_ack_pld;
	
	assign A0_out0_ack_mst_id = D0_in0_ack_mst_id;
	
	assign A0_out0_ack_slv_id = D0_in0_ack_slv_id;
	
	assign D0_clk = clk;
	
	assign D0_rst_n = rst_n;
	
	assign D0_out0_req_rdy = M0_in0_req_rdy;
	
	assign D0_out1_req_rdy = M1_in0_req_rdy;
	
	assign D0_out0_ack_vld = M0_in0_ack_vld;
	
	assign D0_out1_ack_vld = M1_in0_ack_vld;
	
	assign D0_out0_ack_head = M0_in0_ack_head;
	
	assign D0_out1_ack_head = M1_in0_ack_head;
	
	assign D0_out0_ack_tail = M0_in0_ack_tail;
	
	assign D0_out1_ack_tail = M1_in0_ack_tail;
	
	assign D0_out0_ack_pld = M0_in0_ack_pld;
	
	assign D0_out1_ack_pld = M1_in0_ack_pld;
	
	assign D0_out0_ack_mst_id = M0_in0_ack_mst_id;
	
	assign D0_out1_ack_mst_id = M1_in0_ack_mst_id;
	
	assign D0_out0_ack_slv_id = M0_in0_ack_slv_id;
	
	assign D0_out1_ack_slv_id = M1_in0_ack_slv_id;
	
	assign D0_in0_req_vld = A0_out0_req_vld;
	
	assign D0_in0_req_head = A0_out0_req_head;
	
	assign D0_in0_req_tail = A0_out0_req_tail;
	
	assign D0_in0_req_pld = A0_out0_req_pld;
	
	assign D0_in0_req_mst_id = A0_out0_req_mst_id;
	
	assign D0_in0_req_slv_id = A0_out0_req_slv_id;
	
	assign D0_in0_ack_rdy = A0_out0_ack_rdy;
	
	assign M0_clk = clk;
	
	assign M0_rst_n = rst_n;
	
	assign M0_out_aw_rdy = D_M0_out_aw_rdy;
	
	assign M0_out_w_rdy = D_M0_out_w_rdy;
	
	assign M0_out_b_vld = D_M0_out_b_vld;
	
	assign M0_out_b_id = D_M0_out_b_id;
	
	assign M0_out_b_resp = D_M0_out_b_resp;
	
	assign M0_in0_req_vld = D0_out0_req_vld;
	
	assign M0_in0_req_head = D0_out0_req_head;
	
	assign M0_in0_req_tail = D0_out0_req_tail;
	
	assign M0_in0_req_pld = D0_out0_req_pld;
	
	assign M0_in0_req_mst_id = D0_out0_req_mst_id;
	
	assign M0_in0_req_slv_id = D0_out0_req_slv_id;
	
	assign M0_in0_ack_rdy = D0_out0_ack_rdy;
	
	assign M0_out_ar_rdy = D_M0_out_ar_rdy;
	
	assign M0_out_r_vld = D_M0_out_r_vld;
	
	assign M0_out_r_id = D_M0_out_r_id;
	
	assign M0_out_r_data = D_M0_out_r_data;
	
	assign M0_out_r_resp = D_M0_out_r_resp;
	
	assign M0_out_r_last = D_M0_out_r_last;
	
	assign M1_clk = clk;
	
	assign M1_rst_n = rst_n;
	
	assign M1_out_aw_rdy = D_M1_out_aw_rdy;
	
	assign M1_out_w_rdy = D_M1_out_w_rdy;
	
	assign M1_out_b_vld = D_M1_out_b_vld;
	
	assign M1_out_b_id = D_M1_out_b_id;
	
	assign M1_out_b_resp = D_M1_out_b_resp;
	
	assign M1_in0_req_vld = D0_out1_req_vld;
	
	assign M1_in0_req_head = D0_out1_req_head;
	
	assign M1_in0_req_tail = D0_out1_req_tail;
	
	assign M1_in0_req_pld = D0_out1_req_pld;
	
	assign M1_in0_req_mst_id = D0_out1_req_mst_id;
	
	assign M1_in0_req_slv_id = D0_out1_req_slv_id;
	
	assign M1_in0_ack_rdy = D0_out1_ack_rdy;
	
	assign M1_out_ar_rdy = D_M1_out_ar_rdy;
	
	assign M1_out_r_vld = D_M1_out_r_vld;
	
	assign M1_out_r_id = D_M1_out_r_id;
	
	assign M1_out_r_data = D_M1_out_r_data;
	
	assign M1_out_r_resp = D_M1_out_r_resp;
	
	assign M1_out_r_last = D_M1_out_r_last;
	
	DSlvAxi_node_S0 S0 (
		.clk(S0_clk),
		.rst_n(S0_rst_n),
		.in_aw_vld(S0_in_aw_vld),
		.in_aw_rdy(S0_in_aw_rdy),
		.in_aw_addr(S0_in_aw_addr),
		.in_aw_id(S0_in_aw_id),
		.in_aw_user(S0_in_aw_user),
		.in_w_vld(S0_in_w_vld),
		.in_w_rdy(S0_in_w_rdy),
		.in_w_last(S0_in_w_last),
		.in_w_strb(S0_in_w_strb),
		.in_w_data(S0_in_w_data),
		.in_b_vld(S0_in_b_vld),
		.in_b_rdy(S0_in_b_rdy),
		.in_b_id(S0_in_b_id),
		.in_b_resp(S0_in_b_resp),
		.out0_req_vld(S0_out0_req_vld),
		.out0_req_rdy(S0_out0_req_rdy),
		.out0_req_head(S0_out0_req_head),
		.out0_req_tail(S0_out0_req_tail),
		.out0_req_pld(S0_out0_req_pld),
		.out0_req_mst_id(S0_out0_req_mst_id),
		.out0_req_slv_id(S0_out0_req_slv_id),
		.out0_ack_vld(S0_out0_ack_vld),
		.out0_ack_rdy(S0_out0_ack_rdy),
		.out0_ack_head(S0_out0_ack_head),
		.out0_ack_tail(S0_out0_ack_tail),
		.out0_ack_pld(S0_out0_ack_pld),
		.out0_ack_mst_id(S0_out0_ack_mst_id),
		.out0_ack_slv_id(S0_out0_ack_slv_id));
	DSlvAxi_node_S1 S1 (
		.clk(S1_clk),
		.rst_n(S1_rst_n),
		.in_aw_vld(S1_in_aw_vld),
		.in_aw_rdy(S1_in_aw_rdy),
		.in_aw_addr(S1_in_aw_addr),
		.in_aw_id(S1_in_aw_id),
		.in_aw_user(S1_in_aw_user),
		.in_w_vld(S1_in_w_vld),
		.in_w_rdy(S1_in_w_rdy),
		.in_w_last(S1_in_w_last),
		.in_w_strb(S1_in_w_strb),
		.in_w_data(S1_in_w_data),
		.in_b_vld(S1_in_b_vld),
		.in_b_rdy(S1_in_b_rdy),
		.in_b_id(S1_in_b_id),
		.in_b_resp(S1_in_b_resp),
		.out0_req_vld(S1_out0_req_vld),
		.out0_req_rdy(S1_out0_req_rdy),
		.out0_req_head(S1_out0_req_head),
		.out0_req_tail(S1_out0_req_tail),
		.out0_req_pld(S1_out0_req_pld),
		.out0_req_mst_id(S1_out0_req_mst_id),
		.out0_req_slv_id(S1_out0_req_slv_id),
		.out0_ack_vld(S1_out0_ack_vld),
		.out0_ack_rdy(S1_out0_ack_rdy),
		.out0_ack_head(S1_out0_ack_head),
		.out0_ack_tail(S1_out0_ack_tail),
		.out0_ack_pld(S1_out0_ack_pld),
		.out0_ack_mst_id(S1_out0_ack_mst_id),
		.out0_ack_slv_id(S1_out0_ack_slv_id));
	DArbDual_node_A0 A0 (
		.clk(A0_clk),
		.rst_n(A0_rst_n),
		.in0_req_vld(A0_in0_req_vld),
		.in1_req_vld(A0_in1_req_vld),
		.in0_req_rdy(A0_in0_req_rdy),
		.in1_req_rdy(A0_in1_req_rdy),
		.in0_req_head(A0_in0_req_head),
		.in1_req_head(A0_in1_req_head),
		.in0_req_tail(A0_in0_req_tail),
		.in1_req_tail(A0_in1_req_tail),
		.in0_req_pld(A0_in0_req_pld),
		.in1_req_pld(A0_in1_req_pld),
		.in0_req_mst_id(A0_in0_req_mst_id),
		.in1_req_mst_id(A0_in1_req_mst_id),
		.in0_req_slv_id(A0_in0_req_slv_id),
		.in1_req_slv_id(A0_in1_req_slv_id),
		.in0_ack_vld(A0_in0_ack_vld),
		.in1_ack_vld(A0_in1_ack_vld),
		.in0_ack_rdy(A0_in0_ack_rdy),
		.in1_ack_rdy(A0_in1_ack_rdy),
		.in0_ack_head(A0_in0_ack_head),
		.in1_ack_head(A0_in1_ack_head),
		.in0_ack_tail(A0_in0_ack_tail),
		.in1_ack_tail(A0_in1_ack_tail),
		.in0_ack_pld(A0_in0_ack_pld),
		.in1_ack_pld(A0_in1_ack_pld),
		.in0_ack_mst_id(A0_in0_ack_mst_id),
		.in1_ack_mst_id(A0_in1_ack_mst_id),
		.in0_ack_slv_id(A0_in0_ack_slv_id),
		.in1_ack_slv_id(A0_in1_ack_slv_id),
		.out0_req_vld(A0_out0_req_vld),
		.out0_req_rdy(A0_out0_req_rdy),
		.out0_req_head(A0_out0_req_head),
		.out0_req_tail(A0_out0_req_tail),
		.out0_req_pld(A0_out0_req_pld),
		.out0_req_mst_id(A0_out0_req_mst_id),
		.out0_req_slv_id(A0_out0_req_slv_id),
		.out0_ack_vld(A0_out0_ack_vld),
		.out0_ack_rdy(A0_out0_ack_rdy),
		.out0_ack_head(A0_out0_ack_head),
		.out0_ack_tail(A0_out0_ack_tail),
		.out0_ack_pld(A0_out0_ack_pld),
		.out0_ack_mst_id(A0_out0_ack_mst_id),
		.out0_ack_slv_id(A0_out0_ack_slv_id));
	DDecDual_node_D0 D0 (
		.clk(D0_clk),
		.rst_n(D0_rst_n),
		.out0_req_vld(D0_out0_req_vld),
		.out1_req_vld(D0_out1_req_vld),
		.out0_req_rdy(D0_out0_req_rdy),
		.out1_req_rdy(D0_out1_req_rdy),
		.out0_req_head(D0_out0_req_head),
		.out1_req_head(D0_out1_req_head),
		.out0_req_tail(D0_out0_req_tail),
		.out1_req_tail(D0_out1_req_tail),
		.out0_req_pld(D0_out0_req_pld),
		.out1_req_pld(D0_out1_req_pld),
		.out0_req_mst_id(D0_out0_req_mst_id),
		.out1_req_mst_id(D0_out1_req_mst_id),
		.out0_req_slv_id(D0_out0_req_slv_id),
		.out1_req_slv_id(D0_out1_req_slv_id),
		.out0_ack_vld(D0_out0_ack_vld),
		.out1_ack_vld(D0_out1_ack_vld),
		.out0_ack_rdy(D0_out0_ack_rdy),
		.out1_ack_rdy(D0_out1_ack_rdy),
		.out0_ack_head(D0_out0_ack_head),
		.out1_ack_head(D0_out1_ack_head),
		.out0_ack_tail(D0_out0_ack_tail),
		.out1_ack_tail(D0_out1_ack_tail),
		.out0_ack_pld(D0_out0_ack_pld),
		.out1_ack_pld(D0_out1_ack_pld),
		.out0_ack_mst_id(D0_out0_ack_mst_id),
		.out1_ack_mst_id(D0_out1_ack_mst_id),
		.out0_ack_slv_id(D0_out0_ack_slv_id),
		.out1_ack_slv_id(D0_out1_ack_slv_id),
		.in0_req_vld(D0_in0_req_vld),
		.in0_req_rdy(D0_in0_req_rdy),
		.in0_req_head(D0_in0_req_head),
		.in0_req_tail(D0_in0_req_tail),
		.in0_req_pld(D0_in0_req_pld),
		.in0_req_mst_id(D0_in0_req_mst_id),
		.in0_req_slv_id(D0_in0_req_slv_id),
		.in0_ack_vld(D0_in0_ack_vld),
		.in0_ack_rdy(D0_in0_ack_rdy),
		.in0_ack_head(D0_in0_ack_head),
		.in0_ack_tail(D0_in0_ack_tail),
		.in0_ack_pld(D0_in0_ack_pld),
		.in0_ack_mst_id(D0_in0_ack_mst_id),
		.in0_ack_slv_id(D0_in0_ack_slv_id));
	DMstAxi_node_M0 M0 (
		.clk(M0_clk),
		.rst_n(M0_rst_n),
		.out_aw_vld(M0_out_aw_vld),
		.out_aw_rdy(M0_out_aw_rdy),
		.out_aw_addr(M0_out_aw_addr),
		.out_aw_id(M0_out_aw_id),
		.out_aw_user(M0_out_aw_user),
		.out_w_vld(M0_out_w_vld),
		.out_w_rdy(M0_out_w_rdy),
		.out_w_last(M0_out_w_last),
		.out_w_strb(M0_out_w_strb),
		.out_w_data(M0_out_w_data),
		.out_b_vld(M0_out_b_vld),
		.out_b_rdy(M0_out_b_rdy),
		.out_b_id(M0_out_b_id),
		.out_b_resp(M0_out_b_resp),
		.in0_req_vld(M0_in0_req_vld),
		.in0_req_rdy(M0_in0_req_rdy),
		.in0_req_head(M0_in0_req_head),
		.in0_req_tail(M0_in0_req_tail),
		.in0_req_pld(M0_in0_req_pld),
		.in0_req_mst_id(M0_in0_req_mst_id),
		.in0_req_slv_id(M0_in0_req_slv_id),
		.in0_ack_vld(M0_in0_ack_vld),
		.in0_ack_rdy(M0_in0_ack_rdy),
		.in0_ack_head(M0_in0_ack_head),
		.in0_ack_tail(M0_in0_ack_tail),
		.in0_ack_pld(M0_in0_ack_pld),
		.in0_ack_mst_id(M0_in0_ack_mst_id),
		.in0_ack_slv_id(M0_in0_ack_slv_id),
		.out_ar_vld(M0_out_ar_vld),
		.out_ar_rdy(M0_out_ar_rdy),
		.out_ar_addr(M0_out_ar_addr),
		.out_ar_id(M0_out_ar_id),
		.out_ar_user(M0_out_ar_user),
		.out_r_vld(M0_out_r_vld),
		.out_r_rdy(M0_out_r_rdy),
		.out_r_id(M0_out_r_id),
		.out_r_data(M0_out_r_data),
		.out_r_resp(M0_out_r_resp),
		.out_r_last(M0_out_r_last),
		.in0_r_req_vld(M0_in0_r_req_vld),
		.in0_r_req_rdy(M0_in0_r_req_rdy),
		.in0_r_req_head(M0_in0_r_req_head),
		.in0_r_req_tail(M0_in0_r_req_tail),
		.in0_r_req_pld(M0_in0_r_req_pld),
		.in0_r_req_mst_id(M0_in0_r_req_mst_id),
		.in0_r_req_slv_id(M0_in0_r_req_slv_id),
		.in0_r_ack_vld(M0_in0_r_ack_vld),
		.in0_r_ack_rdy(M0_in0_r_ack_rdy),
		.in0_r_ack_head(M0_in0_r_ack_head),
		.in0_r_ack_tail(M0_in0_r_ack_tail),
		.in0_r_ack_pld(M0_in0_r_ack_pld),
		.in0_r_ack_mst_id(M0_in0_r_ack_mst_id),
		.in0_r_ack_slv_id(M0_in0_r_ack_slv_id));
	DMstAxi_node_M1 M1 (
		.clk(M1_clk),
		.rst_n(M1_rst_n),
		.out_aw_vld(M1_out_aw_vld),
		.out_aw_rdy(M1_out_aw_rdy),
		.out_aw_addr(M1_out_aw_addr),
		.out_aw_id(M1_out_aw_id),
		.out_aw_user(M1_out_aw_user),
		.out_w_vld(M1_out_w_vld),
		.out_w_rdy(M1_out_w_rdy),
		.out_w_last(M1_out_w_last),
		.out_w_strb(M1_out_w_strb),
		.out_w_data(M1_out_w_data),
		.out_b_vld(M1_out_b_vld),
		.out_b_rdy(M1_out_b_rdy),
		.out_b_id(M1_out_b_id),
		.out_b_resp(M1_out_b_resp),
		.in0_req_vld(M1_in0_req_vld),
		.in0_req_rdy(M1_in0_req_rdy),
		.in0_req_head(M1_in0_req_head),
		.in0_req_tail(M1_in0_req_tail),
		.in0_req_pld(M1_in0_req_pld),
		.in0_req_mst_id(M1_in0_req_mst_id),
		.in0_req_slv_id(M1_in0_req_slv_id),
		.in0_ack_vld(M1_in0_ack_vld),
		.in0_ack_rdy(M1_in0_ack_rdy),
		.in0_ack_head(M1_in0_ack_head),
		.in0_ack_tail(M1_in0_ack_tail),
		.in0_ack_pld(M1_in0_ack_pld),
		.in0_ack_mst_id(M1_in0_ack_mst_id),
		.in0_ack_slv_id(M1_in0_ack_slv_id),
		.out_ar_vld(M1_out_ar_vld),
		.out_ar_rdy(M1_out_ar_rdy),
		.out_ar_addr(M1_out_ar_addr),
		.out_ar_id(M1_out_ar_id),
		.out_ar_user(M1_out_ar_user),
		.out_r_vld(M1_out_r_vld),
		.out_r_rdy(M1_out_r_rdy),
		.out_r_id(M1_out_r_id),
		.out_r_data(M1_out_r_data),
		.out_r_resp(M1_out_r_resp),
		.out_r_last(M1_out_r_last),
		.in0_r_req_vld(M1_in0_r_req_vld),
		.in0_r_req_rdy(M1_in0_r_req_rdy),
		.in0_r_req_head(M1_in0_r_req_head),
		.in0_r_req_tail(M1_in0_r_req_tail),
		.in0_r_req_pld(M1_in0_r_req_pld),
		.in0_r_req_mst_id(M1_in0_r_req_mst_id),
		.in0_r_req_slv_id(M1_in0_r_req_slv_id),
		.in0_r_ack_vld(M1_in0_r_ack_vld),
		.in0_r_ack_rdy(M1_in0_r_ack_rdy),
		.in0_r_ack_head(M1_in0_r_ack_head),
		.in0_r_ack_tail(M1_in0_r_ack_tail),
		.in0_r_ack_pld(M1_in0_r_ack_pld),
		.in0_r_ack_mst_id(M1_in0_r_ack_mst_id),
		.in0_r_ack_slv_id(M1_in0_r_ack_slv_id));

endmodule
//[UHDL]Content End [md5:1ab29aeac5f1b956084fd4c3681662ca]

//[UHDL]Parameter Start [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]Parameter End [md5:d41d8cd98f00b204e9800998ecf8427e]

