//==========================================================================================================================
//Key is used to ensure the consistency of file version and content, and cannot be modified.
//Version Control is the version number written when the file is generated and cannot be modified.
//ToolMessage is used to record related information of any tool that has processed the file and cannot be manually modified.
//UserMessage is used by the user to write any information, which can be modified in any way.
//Content is the actual payload of the file.
//Parameter is the additional parameter information carried by the file and cannot be modified in any way.

//Key is generated by the hash of Version Control, Content and Parameter to ensure the consistency of the file.
//These three parts do not allow any individual modification
//==========================================================================================================================


//[UHDL]Key Start [md5:56616a527c4527a6b4ee44462d01233b]
//Version Control Hash: 3accddf64b1dd03abeb9b0b3e5a7ba44
//Content Hash: ae592e51cf1222e6cafc52f45ad6165a
//Parameter Hash: d41d8cd98f00b204e9800998ecf8427e
//[UHDL]Key End [md5:56616a527c4527a6b4ee44462d01233b]

//[UHDL]Version Control Start [md5:3accddf64b1dd03abeb9b0b3e5a7ba44]
//[UHDL]Version Control Version:1.0.1
//[UHDL]Version Control End [md5:3accddf64b1dd03abeb9b0b3e5a7ba44]

//[UHDL]Tool Message Start [md5:bae600ef297a3423865d474e391c5285]
//Written by UHDL in 2022-09-11 22:34:00
//[UHDL]Tool Message End [md5:bae600ef297a3423865d474e391c5285]

//[UHDL]User Message Start [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]User Message End [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]Content Start [md5:ae592e51cf1222e6cafc52f45ad6165a]
module DWrap_network_network0 (
	input         clk              ,
	input         rst_n            ,
	input         D_S1_in0_aw_vld  ,
	output        D_S1_in0_aw_rdy  ,
	input  [31:0] D_S1_in0_aw_addr ,
	input  [7:0]  D_S1_in0_aw_id   ,
	input  [31:0] D_S1_in0_aw_user ,
	input         D_S1_in0_w_vld   ,
	output        D_S1_in0_w_rdy   ,
	input         D_S1_in0_w_last  ,
	input  [31:0] D_S1_in0_w_data  ,
	input  [3:0]  D_S1_in0_w_strb  ,
	input  [31:0] D_S1_in0_w_user  ,
	output        D_S1_in0_b_vld   ,
	input         D_S1_in0_b_rdy   ,
	output [7:0]  D_S1_in0_b_id    ,
	output [1:0]  D_S1_in0_b_resp  ,
	input         D_S1_in0_ar_vld  ,
	output        D_S1_in0_ar_rdy  ,
	input  [31:0] D_S1_in0_ar_addr ,
	input  [7:0]  D_S1_in0_ar_id   ,
	input  [31:0] D_S1_in0_ar_user ,
	output        D_S1_in0_r_vld   ,
	input         D_S1_in0_r_rdy   ,
	output [7:0]  D_S1_in0_r_id    ,
	output [31:0] D_S1_in0_r_data  ,
	output [1:0]  D_S1_in0_r_resp  ,
	output        D_S1_in0_r_last  ,
	input         D_S2_in0_aw_vld  ,
	output        D_S2_in0_aw_rdy  ,
	input  [31:0] D_S2_in0_aw_addr ,
	input  [7:0]  D_S2_in0_aw_id   ,
	input  [31:0] D_S2_in0_aw_user ,
	input         D_S2_in0_w_vld   ,
	output        D_S2_in0_w_rdy   ,
	input         D_S2_in0_w_last  ,
	input  [31:0] D_S2_in0_w_data  ,
	input  [3:0]  D_S2_in0_w_strb  ,
	input  [31:0] D_S2_in0_w_user  ,
	output        D_S2_in0_b_vld   ,
	input         D_S2_in0_b_rdy   ,
	output [7:0]  D_S2_in0_b_id    ,
	output [1:0]  D_S2_in0_b_resp  ,
	input         D_S2_in0_ar_vld  ,
	output        D_S2_in0_ar_rdy  ,
	input  [31:0] D_S2_in0_ar_addr ,
	input  [7:0]  D_S2_in0_ar_id   ,
	input  [31:0] D_S2_in0_ar_user ,
	output        D_S2_in0_r_vld   ,
	input         D_S2_in0_r_rdy   ,
	output [7:0]  D_S2_in0_r_id    ,
	output [31:0] D_S2_in0_r_data  ,
	output [1:0]  D_S2_in0_r_resp  ,
	output        D_S2_in0_r_last  ,
	output        D_M1_out0_aw_vld ,
	input         D_M1_out0_aw_rdy ,
	output [31:0] D_M1_out0_aw_addr,
	output [11:0] D_M1_out0_aw_id  ,
	output [31:0] D_M1_out0_aw_user,
	output        D_M1_out0_w_vld  ,
	input         D_M1_out0_w_rdy  ,
	output        D_M1_out0_w_last ,
	output [31:0] D_M1_out0_w_data ,
	output [3:0]  D_M1_out0_w_strb ,
	output [31:0] D_M1_out0_w_user ,
	input         D_M1_out0_b_vld  ,
	output        D_M1_out0_b_rdy  ,
	input  [11:0] D_M1_out0_b_id   ,
	input  [1:0]  D_M1_out0_b_resp ,
	output        D_M1_out0_ar_vld ,
	input         D_M1_out0_ar_rdy ,
	output [31:0] D_M1_out0_ar_addr,
	output [11:0] D_M1_out0_ar_id  ,
	output [31:0] D_M1_out0_ar_user,
	input         D_M1_out0_r_vld  ,
	output        D_M1_out0_r_rdy  ,
	input  [11:0] D_M1_out0_r_id   ,
	input  [31:0] D_M1_out0_r_data ,
	input  [1:0]  D_M1_out0_r_resp ,
	input         D_M1_out0_r_last ,
	output        D_M2_out0_aw_vld ,
	input         D_M2_out0_aw_rdy ,
	output [31:0] D_M2_out0_aw_addr,
	output [11:0] D_M2_out0_aw_id  ,
	output [31:0] D_M2_out0_aw_user,
	output        D_M2_out0_w_vld  ,
	input         D_M2_out0_w_rdy  ,
	output        D_M2_out0_w_last ,
	output [31:0] D_M2_out0_w_data ,
	output [3:0]  D_M2_out0_w_strb ,
	output [31:0] D_M2_out0_w_user ,
	input         D_M2_out0_b_vld  ,
	output        D_M2_out0_b_rdy  ,
	input  [11:0] D_M2_out0_b_id   ,
	input  [1:0]  D_M2_out0_b_resp ,
	output        D_M2_out0_ar_vld ,
	input         D_M2_out0_ar_rdy ,
	output [31:0] D_M2_out0_ar_addr,
	output [11:0] D_M2_out0_ar_id  ,
	output [31:0] D_M2_out0_ar_user,
	input         D_M2_out0_r_vld  ,
	output        D_M2_out0_r_rdy  ,
	input  [11:0] D_M2_out0_r_id   ,
	input  [31:0] D_M2_out0_r_data ,
	input  [1:0]  D_M2_out0_r_resp ,
	input         D_M2_out0_r_last );
	wire        S1_clk              ;
	wire        S1_rst_n            ;
	wire        S1_out0_r_req_vld   ;
	wire        S1_out0_r_req_rdy   ;
	wire        S1_out0_r_req_head  ;
	wire        S1_out0_r_req_tail  ;
	wire [63:0] S1_out0_r_req_pld   ;
	wire [3:0]  S1_out0_r_req_src_id;
	wire [3:0]  S1_out0_r_req_tgt_id;
	wire [7:0]  S1_out0_r_req_txn_id;
	wire        S1_out0_w_req_vld   ;
	wire        S1_out0_w_req_rdy   ;
	wire        S1_out0_w_req_head  ;
	wire        S1_out0_w_req_tail  ;
	wire [99:0] S1_out0_w_req_pld   ;
	wire [3:0]  S1_out0_w_req_src_id;
	wire [3:0]  S1_out0_w_req_tgt_id;
	wire [7:0]  S1_out0_w_req_txn_id;
	wire        S1_out0_r_ack_vld   ;
	wire        S1_out0_r_ack_rdy   ;
	wire        S1_out0_r_ack_head  ;
	wire        S1_out0_r_ack_tail  ;
	wire [34:0] S1_out0_r_ack_pld   ;
	wire [3:0]  S1_out0_r_ack_src_id;
	wire [3:0]  S1_out0_r_ack_tgt_id;
	wire [7:0]  S1_out0_r_ack_txn_id;
	wire        S1_out0_w_ack_vld   ;
	wire        S1_out0_w_ack_rdy   ;
	wire        S1_out0_w_ack_head  ;
	wire        S1_out0_w_ack_tail  ;
	wire [1:0]  S1_out0_w_ack_pld   ;
	wire [3:0]  S1_out0_w_ack_src_id;
	wire [3:0]  S1_out0_w_ack_tgt_id;
	wire [7:0]  S1_out0_w_ack_txn_id;
	wire        S1_in0_aw_vld       ;
	wire        S1_in0_aw_rdy       ;
	wire [31:0] S1_in0_aw_addr      ;
	wire [7:0]  S1_in0_aw_id        ;
	wire [31:0] S1_in0_aw_user      ;
	wire        S1_in0_w_vld        ;
	wire        S1_in0_w_rdy        ;
	wire        S1_in0_w_last       ;
	wire [31:0] S1_in0_w_data       ;
	wire [3:0]  S1_in0_w_strb       ;
	wire [31:0] S1_in0_w_user       ;
	wire        S1_in0_b_vld        ;
	wire        S1_in0_b_rdy        ;
	wire [7:0]  S1_in0_b_id         ;
	wire [1:0]  S1_in0_b_resp       ;
	wire        S1_in0_ar_vld       ;
	wire        S1_in0_ar_rdy       ;
	wire [31:0] S1_in0_ar_addr      ;
	wire [7:0]  S1_in0_ar_id        ;
	wire [31:0] S1_in0_ar_user      ;
	wire        S1_in0_r_vld        ;
	wire        S1_in0_r_rdy        ;
	wire [7:0]  S1_in0_r_id         ;
	wire [31:0] S1_in0_r_data       ;
	wire [1:0]  S1_in0_r_resp       ;
	wire        S1_in0_r_last       ;
	wire        S2_clk              ;
	wire        S2_rst_n            ;
	wire        S2_out0_r_req_vld   ;
	wire        S2_out0_r_req_rdy   ;
	wire        S2_out0_r_req_head  ;
	wire        S2_out0_r_req_tail  ;
	wire [63:0] S2_out0_r_req_pld   ;
	wire [3:0]  S2_out0_r_req_src_id;
	wire [3:0]  S2_out0_r_req_tgt_id;
	wire [7:0]  S2_out0_r_req_txn_id;
	wire        S2_out0_w_req_vld   ;
	wire        S2_out0_w_req_rdy   ;
	wire        S2_out0_w_req_head  ;
	wire        S2_out0_w_req_tail  ;
	wire [99:0] S2_out0_w_req_pld   ;
	wire [3:0]  S2_out0_w_req_src_id;
	wire [3:0]  S2_out0_w_req_tgt_id;
	wire [7:0]  S2_out0_w_req_txn_id;
	wire        S2_out0_r_ack_vld   ;
	wire        S2_out0_r_ack_rdy   ;
	wire        S2_out0_r_ack_head  ;
	wire        S2_out0_r_ack_tail  ;
	wire [34:0] S2_out0_r_ack_pld   ;
	wire [3:0]  S2_out0_r_ack_src_id;
	wire [3:0]  S2_out0_r_ack_tgt_id;
	wire [7:0]  S2_out0_r_ack_txn_id;
	wire        S2_out0_w_ack_vld   ;
	wire        S2_out0_w_ack_rdy   ;
	wire        S2_out0_w_ack_head  ;
	wire        S2_out0_w_ack_tail  ;
	wire [1:0]  S2_out0_w_ack_pld   ;
	wire [3:0]  S2_out0_w_ack_src_id;
	wire [3:0]  S2_out0_w_ack_tgt_id;
	wire [7:0]  S2_out0_w_ack_txn_id;
	wire        S2_in0_aw_vld       ;
	wire        S2_in0_aw_rdy       ;
	wire [31:0] S2_in0_aw_addr      ;
	wire [7:0]  S2_in0_aw_id        ;
	wire [31:0] S2_in0_aw_user      ;
	wire        S2_in0_w_vld        ;
	wire        S2_in0_w_rdy        ;
	wire        S2_in0_w_last       ;
	wire [31:0] S2_in0_w_data       ;
	wire [3:0]  S2_in0_w_strb       ;
	wire [31:0] S2_in0_w_user       ;
	wire        S2_in0_b_vld        ;
	wire        S2_in0_b_rdy        ;
	wire [7:0]  S2_in0_b_id         ;
	wire [1:0]  S2_in0_b_resp       ;
	wire        S2_in0_ar_vld       ;
	wire        S2_in0_ar_rdy       ;
	wire [31:0] S2_in0_ar_addr      ;
	wire [7:0]  S2_in0_ar_id        ;
	wire [31:0] S2_in0_ar_user      ;
	wire        S2_in0_r_vld        ;
	wire        S2_in0_r_rdy        ;
	wire [7:0]  S2_in0_r_id         ;
	wire [31:0] S2_in0_r_data       ;
	wire [1:0]  S2_in0_r_resp       ;
	wire        S2_in0_r_last       ;
	wire        A0_clk              ;
	wire        A0_rst_n            ;
	wire        A0_out0_w_req_vld   ;
	wire        A0_out0_w_req_rdy   ;
	wire        A0_out0_w_req_head  ;
	wire        A0_out0_w_req_tail  ;
	wire [99:0] A0_out0_w_req_pld   ;
	wire [3:0]  A0_out0_w_req_src_id;
	wire [3:0]  A0_out0_w_req_tgt_id;
	wire [7:0]  A0_out0_w_req_txn_id;
	wire        A0_out0_r_req_vld   ;
	wire        A0_out0_r_req_rdy   ;
	wire        A0_out0_r_req_head  ;
	wire        A0_out0_r_req_tail  ;
	wire [63:0] A0_out0_r_req_pld   ;
	wire [3:0]  A0_out0_r_req_src_id;
	wire [3:0]  A0_out0_r_req_tgt_id;
	wire [7:0]  A0_out0_r_req_txn_id;
	wire        A0_out0_w_ack_vld   ;
	wire        A0_out0_w_ack_rdy   ;
	wire        A0_out0_w_ack_head  ;
	wire        A0_out0_w_ack_tail  ;
	wire [1:0]  A0_out0_w_ack_pld   ;
	wire [3:0]  A0_out0_w_ack_src_id;
	wire [3:0]  A0_out0_w_ack_tgt_id;
	wire [7:0]  A0_out0_w_ack_txn_id;
	wire        A0_out0_r_ack_vld   ;
	wire        A0_out0_r_ack_rdy   ;
	wire        A0_out0_r_ack_head  ;
	wire        A0_out0_r_ack_tail  ;
	wire [34:0] A0_out0_r_ack_pld   ;
	wire [3:0]  A0_out0_r_ack_src_id;
	wire [3:0]  A0_out0_r_ack_tgt_id;
	wire [7:0]  A0_out0_r_ack_txn_id;
	wire        A0_in0_w_req_vld    ;
	wire        A0_in0_w_req_dy     ;
	wire        A0_in0_w_req_head   ;
	wire        A0_in0_w_req_ail    ;
	wire [99:0] A0_in0_w_req_pld    ;
	wire [3:0]  A0_in0_w_req_src_id ;
	wire [3:0]  A0_in0_w_req_gt_id  ;
	wire [7:0]  A0_in0_w_req_xn_id  ;
	wire        A0_in1_w_req_vld    ;
	wire        A0_in1_w_req_dy     ;
	wire        A0_in1_w_req_head   ;
	wire        A0_in1_w_req_ail    ;
	wire [99:0] A0_in1_w_req_pld    ;
	wire [3:0]  A0_in1_w_req_src_id ;
	wire [3:0]  A0_in1_w_req_gt_id  ;
	wire [7:0]  A0_in1_w_req_xn_id  ;
	wire        A0_in0_r_req_vld    ;
	wire        A0_in0_r_req_dy     ;
	wire        A0_in0_r_req_head   ;
	wire        A0_in0_r_req_ail    ;
	wire [63:0] A0_in0_r_req_pld    ;
	wire [3:0]  A0_in0_r_req_src_id ;
	wire [3:0]  A0_in0_r_req_gt_id  ;
	wire [7:0]  A0_in0_r_req_xn_id  ;
	wire        A0_in1_r_req_vld    ;
	wire        A0_in1_r_req_dy     ;
	wire        A0_in1_r_req_head   ;
	wire        A0_in1_r_req_ail    ;
	wire [63:0] A0_in1_r_req_pld    ;
	wire [3:0]  A0_in1_r_req_src_id ;
	wire [3:0]  A0_in1_r_req_gt_id  ;
	wire [7:0]  A0_in1_r_req_xn_id  ;
	wire        A0_in0_w_ack_vld    ;
	wire        A0_in0_w_ack_rdy    ;
	wire        A0_in0_w_ack_head   ;
	wire        A0_in0_w_ack_il     ;
	wire [1:0]  A0_in0_w_ack_pld    ;
	wire [3:0]  A0_in0_w_ack_src_id ;
	wire [3:0]  A0_in0_w_ack_gt_id  ;
	wire [7:0]  A0_in0_w_ack_xn_id  ;
	wire        A0_in1_w_ack_vld    ;
	wire        A0_in1_w_ack_rdy    ;
	wire        A0_in1_w_ack_head   ;
	wire        A0_in1_w_ack_il     ;
	wire [1:0]  A0_in1_w_ack_pld    ;
	wire [3:0]  A0_in1_w_ack_src_id ;
	wire [3:0]  A0_in1_w_ack_gt_id  ;
	wire [7:0]  A0_in1_w_ack_xn_id  ;
	wire        A0_in0_r_ack_vld    ;
	wire        A0_in0_r_ack_dy     ;
	wire        A0_in0_r_ack_head   ;
	wire        A0_in0_r_ack_il     ;
	wire [34:0] A0_in0_r_ack_pld    ;
	wire [3:0]  A0_in0_r_ack_src_id ;
	wire [3:0]  A0_in0_r_ack_gt_id  ;
	wire [7:0]  A0_in0_r_ack_xn_id  ;
	wire        A0_in1_r_ack_vld    ;
	wire        A0_in1_r_ack_dy     ;
	wire        A0_in1_r_ack_head   ;
	wire        A0_in1_r_ack_il     ;
	wire [34:0] A0_in1_r_ack_pld    ;
	wire [3:0]  A0_in1_r_ack_src_id ;
	wire [3:0]  A0_in1_r_ack_gt_id  ;
	wire [7:0]  A0_in1_r_ack_xn_id  ;
	wire        D0_clk              ;
	wire        D0_rst_n            ;
	wire        D0_in0_w_req_vld    ;
	wire        D0_in0_w_req_rdy    ;
	wire        D0_in0_w_req_head   ;
	wire        D0_in0_w_req_tail   ;
	wire [99:0] D0_in0_w_req_pld    ;
	wire [3:0]  D0_in0_w_req_src_id ;
	wire [3:0]  D0_in0_w_req_tgt_id ;
	wire [7:0]  D0_in0_w_req_txn_id ;
	wire        D0_in0_r_req_vld    ;
	wire        D0_in0_r_req_rdy    ;
	wire        D0_in0_r_req_head   ;
	wire        D0_in0_r_req_tail   ;
	wire [63:0] D0_in0_r_req_pld    ;
	wire [3:0]  D0_in0_r_req_src_id ;
	wire [3:0]  D0_in0_r_req_tgt_id ;
	wire [7:0]  D0_in0_r_req_txn_id ;
	wire        D0_in0_w_ack_vld    ;
	wire        D0_in0_w_ack_rdy    ;
	wire        D0_in0_w_ack_head   ;
	wire        D0_in0_w_ack_tail   ;
	wire [1:0]  D0_in0_w_ack_pld    ;
	wire [3:0]  D0_in0_w_ack_src_id ;
	wire [3:0]  D0_in0_w_ack_tgt_id ;
	wire [7:0]  D0_in0_w_ack_txn_id ;
	wire        D0_in0_r_ack_vld    ;
	wire        D0_in0_r_ack_rdy    ;
	wire        D0_in0_r_ack_head   ;
	wire        D0_in0_r_ack_tail   ;
	wire [34:0] D0_in0_r_ack_pld    ;
	wire [3:0]  D0_in0_r_ack_src_id ;
	wire [3:0]  D0_in0_r_ack_tgt_id ;
	wire [7:0]  D0_in0_r_ack_txn_id ;
	wire        D0_out0_w_req_vld   ;
	wire        D0_out0_w_req_dy    ;
	wire        D0_out0_w_req_head  ;
	wire        D0_out0_w_req_tail  ;
	wire [99:0] D0_out0_w_req_pld   ;
	wire [3:0]  D0_out0_w_req_src_id;
	wire [3:0]  D0_out0_w_req_tgt_id;
	wire [7:0]  D0_out0_w_req_txn_id;
	wire        D0_out1_w_req_vld   ;
	wire        D0_out1_w_req_dy    ;
	wire        D0_out1_w_req_head  ;
	wire        D0_out1_w_req_tail  ;
	wire [99:0] D0_out1_w_req_pld   ;
	wire [3:0]  D0_out1_w_req_src_id;
	wire [3:0]  D0_out1_w_req_tgt_id;
	wire [7:0]  D0_out1_w_req_txn_id;
	wire        D0_out0_r_req_vld   ;
	wire        D0_out0_r_req_dy    ;
	wire        D0_out0_r_req_head  ;
	wire        D0_out0_r_req_tail  ;
	wire [63:0] D0_out0_r_req_pld   ;
	wire [3:0]  D0_out0_r_req_src_id;
	wire [3:0]  D0_out0_r_req_tgt_id;
	wire [7:0]  D0_out0_r_req_txn_id;
	wire        D0_out1_r_req_vld   ;
	wire        D0_out1_r_req_dy    ;
	wire        D0_out1_r_req_head  ;
	wire        D0_out1_r_req_tail  ;
	wire [63:0] D0_out1_r_req_pld   ;
	wire [3:0]  D0_out1_r_req_src_id;
	wire [3:0]  D0_out1_r_req_tgt_id;
	wire [7:0]  D0_out1_r_req_txn_id;
	wire        D0_out0_w_ack_vld   ;
	wire        D0_out0_w_ack_rdy   ;
	wire        D0_out0_w_ack_head  ;
	wire        D0_out0_w_ack_tail  ;
	wire [1:0]  D0_out0_w_ack_pld   ;
	wire [3:0]  D0_out0_w_ack_src_id;
	wire [3:0]  D0_out0_w_ack_tgt_id;
	wire [7:0]  D0_out0_w_ack_txn_id;
	wire        D0_out1_w_ack_vld   ;
	wire        D0_out1_w_ack_rdy   ;
	wire        D0_out1_w_ack_head  ;
	wire        D0_out1_w_ack_tail  ;
	wire [1:0]  D0_out1_w_ack_pld   ;
	wire [3:0]  D0_out1_w_ack_src_id;
	wire [3:0]  D0_out1_w_ack_tgt_id;
	wire [7:0]  D0_out1_w_ack_txn_id;
	wire        D0_out0_r_ack_vld   ;
	wire        D0_out0_r_ack_dy    ;
	wire        D0_out0_r_ack_head  ;
	wire        D0_out0_r_ack_tail  ;
	wire [34:0] D0_out0_r_ack_pld   ;
	wire [3:0]  D0_out0_r_ack_src_id;
	wire [3:0]  D0_out0_r_ack_tgt_id;
	wire [7:0]  D0_out0_r_ack_txn_id;
	wire        D0_out1_r_ack_vld   ;
	wire        D0_out1_r_ack_dy    ;
	wire        D0_out1_r_ack_head  ;
	wire        D0_out1_r_ack_tail  ;
	wire [34:0] D0_out1_r_ack_pld   ;
	wire [3:0]  D0_out1_r_ack_src_id;
	wire [3:0]  D0_out1_r_ack_tgt_id;
	wire [7:0]  D0_out1_r_ack_txn_id;
	wire        M1_clk              ;
	wire        M1_rst_n            ;
	wire        M1_in0_r_req_vld    ;
	wire        M1_in0_r_req_rdy    ;
	wire        M1_in0_r_req_head   ;
	wire        M1_in0_r_req_tail   ;
	wire [63:0] M1_in0_r_req_pld    ;
	wire [3:0]  M1_in0_r_req_src_id ;
	wire [3:0]  M1_in0_r_req_tgt_id ;
	wire [7:0]  M1_in0_r_req_txn_id ;
	wire        M1_in0_w_req_vld    ;
	wire        M1_in0_w_req_rdy    ;
	wire        M1_in0_w_req_head   ;
	wire        M1_in0_w_req_tail   ;
	wire [99:0] M1_in0_w_req_pld    ;
	wire [3:0]  M1_in0_w_req_src_id ;
	wire [3:0]  M1_in0_w_req_tgt_id ;
	wire [7:0]  M1_in0_w_req_txn_id ;
	wire        M1_in0_r_ack_vld    ;
	wire        M1_in0_r_ack_rdy    ;
	wire        M1_in0_r_ack_head   ;
	wire        M1_in0_r_ack_tail   ;
	wire [34:0] M1_in0_r_ack_pld    ;
	wire [3:0]  M1_in0_r_ack_src_id ;
	wire [3:0]  M1_in0_r_ack_tgt_id ;
	wire [7:0]  M1_in0_r_ack_txn_id ;
	wire        M1_in0_w_ack_vld    ;
	wire        M1_in0_w_ack_rdy    ;
	wire        M1_in0_w_ack_head   ;
	wire        M1_in0_w_ack_tail   ;
	wire [1:0]  M1_in0_w_ack_pld    ;
	wire [3:0]  M1_in0_w_ack_src_id ;
	wire [3:0]  M1_in0_w_ack_tgt_id ;
	wire [7:0]  M1_in0_w_ack_txn_id ;
	wire        M1_out0_aw_vld      ;
	wire        M1_out0_aw_rdy      ;
	wire [31:0] M1_out0_aw_addr     ;
	wire [11:0] M1_out0_aw_id       ;
	wire [31:0] M1_out0_aw_user     ;
	wire        M1_out0_w_vld       ;
	wire        M1_out0_w_rdy       ;
	wire        M1_out0_w_last      ;
	wire [31:0] M1_out0_w_data      ;
	wire [3:0]  M1_out0_w_strb      ;
	wire [31:0] M1_out0_w_user      ;
	wire        M1_out0_b_vld       ;
	wire        M1_out0_b_rdy       ;
	wire [11:0] M1_out0_b_id        ;
	wire [1:0]  M1_out0_b_resp      ;
	wire        M1_out0_ar_vld      ;
	wire        M1_out0_ar_rdy      ;
	wire [31:0] M1_out0_ar_addr     ;
	wire [11:0] M1_out0_ar_id       ;
	wire [31:0] M1_out0_ar_user     ;
	wire        M1_out0_r_vld       ;
	wire        M1_out0_r_rdy       ;
	wire [11:0] M1_out0_r_id        ;
	wire [31:0] M1_out0_r_data      ;
	wire [1:0]  M1_out0_r_resp      ;
	wire        M1_out0_r_last      ;
	wire        M2_clk              ;
	wire        M2_rst_n            ;
	wire        M2_in0_r_req_vld    ;
	wire        M2_in0_r_req_rdy    ;
	wire        M2_in0_r_req_head   ;
	wire        M2_in0_r_req_tail   ;
	wire [63:0] M2_in0_r_req_pld    ;
	wire [3:0]  M2_in0_r_req_src_id ;
	wire [3:0]  M2_in0_r_req_tgt_id ;
	wire [7:0]  M2_in0_r_req_txn_id ;
	wire        M2_in0_w_req_vld    ;
	wire        M2_in0_w_req_rdy    ;
	wire        M2_in0_w_req_head   ;
	wire        M2_in0_w_req_tail   ;
	wire [99:0] M2_in0_w_req_pld    ;
	wire [3:0]  M2_in0_w_req_src_id ;
	wire [3:0]  M2_in0_w_req_tgt_id ;
	wire [7:0]  M2_in0_w_req_txn_id ;
	wire        M2_in0_r_ack_vld    ;
	wire        M2_in0_r_ack_rdy    ;
	wire        M2_in0_r_ack_head   ;
	wire        M2_in0_r_ack_tail   ;
	wire [34:0] M2_in0_r_ack_pld    ;
	wire [3:0]  M2_in0_r_ack_src_id ;
	wire [3:0]  M2_in0_r_ack_tgt_id ;
	wire [7:0]  M2_in0_r_ack_txn_id ;
	wire        M2_in0_w_ack_vld    ;
	wire        M2_in0_w_ack_rdy    ;
	wire        M2_in0_w_ack_head   ;
	wire        M2_in0_w_ack_tail   ;
	wire [1:0]  M2_in0_w_ack_pld    ;
	wire [3:0]  M2_in0_w_ack_src_id ;
	wire [3:0]  M2_in0_w_ack_tgt_id ;
	wire [7:0]  M2_in0_w_ack_txn_id ;
	wire        M2_out0_aw_vld      ;
	wire        M2_out0_aw_rdy      ;
	wire [31:0] M2_out0_aw_addr     ;
	wire [11:0] M2_out0_aw_id       ;
	wire [31:0] M2_out0_aw_user     ;
	wire        M2_out0_w_vld       ;
	wire        M2_out0_w_rdy       ;
	wire        M2_out0_w_last      ;
	wire [31:0] M2_out0_w_data      ;
	wire [3:0]  M2_out0_w_strb      ;
	wire [31:0] M2_out0_w_user      ;
	wire        M2_out0_b_vld       ;
	wire        M2_out0_b_rdy       ;
	wire [11:0] M2_out0_b_id        ;
	wire [1:0]  M2_out0_b_resp      ;
	wire        M2_out0_ar_vld      ;
	wire        M2_out0_ar_rdy      ;
	wire [31:0] M2_out0_ar_addr     ;
	wire [11:0] M2_out0_ar_id       ;
	wire [31:0] M2_out0_ar_user     ;
	wire        M2_out0_r_vld       ;
	wire        M2_out0_r_rdy       ;
	wire [11:0] M2_out0_r_id        ;
	wire [31:0] M2_out0_r_data      ;
	wire [1:0]  M2_out0_r_resp      ;
	wire        M2_out0_r_last      ;
	assign D_S1_in0_aw_rdy = S1_in0_aw_rdy;
	
	assign D_S1_in0_w_rdy = S1_in0_w_rdy;
	
	assign D_S1_in0_b_vld = S1_in0_b_vld;
	
	assign D_S1_in0_b_id = S1_in0_b_id;
	
	assign D_S1_in0_b_resp = S1_in0_b_resp;
	
	assign D_S1_in0_ar_rdy = S1_in0_ar_rdy;
	
	assign D_S1_in0_r_vld = S1_in0_r_vld;
	
	assign D_S1_in0_r_id = S1_in0_r_id;
	
	assign D_S1_in0_r_data = S1_in0_r_data;
	
	assign D_S1_in0_r_resp = S1_in0_r_resp;
	
	assign D_S1_in0_r_last = S1_in0_r_last;
	
	assign D_S2_in0_aw_rdy = S2_in0_aw_rdy;
	
	assign D_S2_in0_w_rdy = S2_in0_w_rdy;
	
	assign D_S2_in0_b_vld = S2_in0_b_vld;
	
	assign D_S2_in0_b_id = S2_in0_b_id;
	
	assign D_S2_in0_b_resp = S2_in0_b_resp;
	
	assign D_S2_in0_ar_rdy = S2_in0_ar_rdy;
	
	assign D_S2_in0_r_vld = S2_in0_r_vld;
	
	assign D_S2_in0_r_id = S2_in0_r_id;
	
	assign D_S2_in0_r_data = S2_in0_r_data;
	
	assign D_S2_in0_r_resp = S2_in0_r_resp;
	
	assign D_S2_in0_r_last = S2_in0_r_last;
	
	assign D_M1_out0_aw_vld = M1_out0_aw_vld;
	
	assign D_M1_out0_aw_addr = M1_out0_aw_addr;
	
	assign D_M1_out0_aw_id = M1_out0_aw_id;
	
	assign D_M1_out0_aw_user = M1_out0_aw_user;
	
	assign D_M1_out0_w_vld = M1_out0_w_vld;
	
	assign D_M1_out0_w_last = M1_out0_w_last;
	
	assign D_M1_out0_w_data = M1_out0_w_data;
	
	assign D_M1_out0_w_strb = M1_out0_w_strb;
	
	assign D_M1_out0_w_user = M1_out0_w_user;
	
	assign D_M1_out0_b_rdy = M1_out0_b_rdy;
	
	assign D_M1_out0_ar_vld = M1_out0_ar_vld;
	
	assign D_M1_out0_ar_addr = M1_out0_ar_addr;
	
	assign D_M1_out0_ar_id = M1_out0_ar_id;
	
	assign D_M1_out0_ar_user = M1_out0_ar_user;
	
	assign D_M1_out0_r_rdy = M1_out0_r_rdy;
	
	assign D_M2_out0_aw_vld = M2_out0_aw_vld;
	
	assign D_M2_out0_aw_addr = M2_out0_aw_addr;
	
	assign D_M2_out0_aw_id = M2_out0_aw_id;
	
	assign D_M2_out0_aw_user = M2_out0_aw_user;
	
	assign D_M2_out0_w_vld = M2_out0_w_vld;
	
	assign D_M2_out0_w_last = M2_out0_w_last;
	
	assign D_M2_out0_w_data = M2_out0_w_data;
	
	assign D_M2_out0_w_strb = M2_out0_w_strb;
	
	assign D_M2_out0_w_user = M2_out0_w_user;
	
	assign D_M2_out0_b_rdy = M2_out0_b_rdy;
	
	assign D_M2_out0_ar_vld = M2_out0_ar_vld;
	
	assign D_M2_out0_ar_addr = M2_out0_ar_addr;
	
	assign D_M2_out0_ar_id = M2_out0_ar_id;
	
	assign D_M2_out0_ar_user = M2_out0_ar_user;
	
	assign D_M2_out0_r_rdy = M2_out0_r_rdy;
	
	assign S1_clk = clk;
	
	assign S1_rst_n = rst_n;
	
	assign S1_out0_r_req_rdy = A0_in0_r_req_dy;
	
	assign S1_out0_w_req_rdy = A0_in0_w_req_dy;
	
	assign S1_out0_r_ack_vld = A0_in0_r_ack_vld;
	
	assign S1_out0_r_ack_head = A0_in0_r_ack_head;
	
	assign S1_out0_r_ack_tail = A0_in0_r_ack_il;
	
	assign S1_out0_r_ack_pld = A0_in0_r_ack_pld;
	
	assign S1_out0_r_ack_src_id = A0_in0_r_ack_src_id;
	
	assign S1_out0_r_ack_tgt_id = A0_in0_r_ack_gt_id;
	
	assign S1_out0_r_ack_txn_id = A0_in0_r_ack_xn_id;
	
	assign S1_out0_w_ack_vld = A0_in0_w_ack_vld;
	
	assign S1_out0_w_ack_head = A0_in0_w_ack_head;
	
	assign S1_out0_w_ack_tail = A0_in0_w_ack_il;
	
	assign S1_out0_w_ack_pld = A0_in0_w_ack_pld;
	
	assign S1_out0_w_ack_src_id = A0_in0_w_ack_src_id;
	
	assign S1_out0_w_ack_tgt_id = A0_in0_w_ack_gt_id;
	
	assign S1_out0_w_ack_txn_id = A0_in0_w_ack_xn_id;
	
	assign S1_in0_aw_vld = D_S1_in0_aw_vld;
	
	assign S1_in0_aw_addr = D_S1_in0_aw_addr;
	
	assign S1_in0_aw_id = D_S1_in0_aw_id;
	
	assign S1_in0_aw_user = D_S1_in0_aw_user;
	
	assign S1_in0_w_vld = D_S1_in0_w_vld;
	
	assign S1_in0_w_last = D_S1_in0_w_last;
	
	assign S1_in0_w_data = D_S1_in0_w_data;
	
	assign S1_in0_w_strb = D_S1_in0_w_strb;
	
	assign S1_in0_w_user = D_S1_in0_w_user;
	
	assign S1_in0_b_rdy = D_S1_in0_b_rdy;
	
	assign S1_in0_ar_vld = D_S1_in0_ar_vld;
	
	assign S1_in0_ar_addr = D_S1_in0_ar_addr;
	
	assign S1_in0_ar_id = D_S1_in0_ar_id;
	
	assign S1_in0_ar_user = D_S1_in0_ar_user;
	
	assign S1_in0_r_rdy = D_S1_in0_r_rdy;
	
	assign S2_clk = clk;
	
	assign S2_rst_n = rst_n;
	
	assign S2_out0_r_req_rdy = A0_in1_r_req_dy;
	
	assign S2_out0_w_req_rdy = A0_in1_w_req_dy;
	
	assign S2_out0_r_ack_vld = A0_in1_r_ack_vld;
	
	assign S2_out0_r_ack_head = A0_in1_r_ack_head;
	
	assign S2_out0_r_ack_tail = A0_in1_r_ack_il;
	
	assign S2_out0_r_ack_pld = A0_in1_r_ack_pld;
	
	assign S2_out0_r_ack_src_id = A0_in1_r_ack_src_id;
	
	assign S2_out0_r_ack_tgt_id = A0_in1_r_ack_gt_id;
	
	assign S2_out0_r_ack_txn_id = A0_in1_r_ack_xn_id;
	
	assign S2_out0_w_ack_vld = A0_in1_w_ack_vld;
	
	assign S2_out0_w_ack_head = A0_in1_w_ack_head;
	
	assign S2_out0_w_ack_tail = A0_in1_w_ack_il;
	
	assign S2_out0_w_ack_pld = A0_in1_w_ack_pld;
	
	assign S2_out0_w_ack_src_id = A0_in1_w_ack_src_id;
	
	assign S2_out0_w_ack_tgt_id = A0_in1_w_ack_gt_id;
	
	assign S2_out0_w_ack_txn_id = A0_in1_w_ack_xn_id;
	
	assign S2_in0_aw_vld = D_S2_in0_aw_vld;
	
	assign S2_in0_aw_addr = D_S2_in0_aw_addr;
	
	assign S2_in0_aw_id = D_S2_in0_aw_id;
	
	assign S2_in0_aw_user = D_S2_in0_aw_user;
	
	assign S2_in0_w_vld = D_S2_in0_w_vld;
	
	assign S2_in0_w_last = D_S2_in0_w_last;
	
	assign S2_in0_w_data = D_S2_in0_w_data;
	
	assign S2_in0_w_strb = D_S2_in0_w_strb;
	
	assign S2_in0_w_user = D_S2_in0_w_user;
	
	assign S2_in0_b_rdy = D_S2_in0_b_rdy;
	
	assign S2_in0_ar_vld = D_S2_in0_ar_vld;
	
	assign S2_in0_ar_addr = D_S2_in0_ar_addr;
	
	assign S2_in0_ar_id = D_S2_in0_ar_id;
	
	assign S2_in0_ar_user = D_S2_in0_ar_user;
	
	assign S2_in0_r_rdy = D_S2_in0_r_rdy;
	
	assign A0_clk = clk;
	
	assign A0_rst_n = rst_n;
	
	assign A0_out0_w_req_rdy = D0_in0_w_req_rdy;
	
	assign A0_out0_r_req_rdy = D0_in0_r_req_rdy;
	
	assign A0_out0_w_ack_vld = D0_in0_w_ack_vld;
	
	assign A0_out0_w_ack_head = D0_in0_w_ack_head;
	
	assign A0_out0_w_ack_tail = D0_in0_w_ack_tail;
	
	assign A0_out0_w_ack_pld = D0_in0_w_ack_pld;
	
	assign A0_out0_w_ack_src_id = D0_in0_w_ack_src_id;
	
	assign A0_out0_w_ack_tgt_id = D0_in0_w_ack_tgt_id;
	
	assign A0_out0_w_ack_txn_id = D0_in0_w_ack_txn_id;
	
	assign A0_out0_r_ack_vld = D0_in0_r_ack_vld;
	
	assign A0_out0_r_ack_head = D0_in0_r_ack_head;
	
	assign A0_out0_r_ack_tail = D0_in0_r_ack_tail;
	
	assign A0_out0_r_ack_pld = D0_in0_r_ack_pld;
	
	assign A0_out0_r_ack_src_id = D0_in0_r_ack_src_id;
	
	assign A0_out0_r_ack_tgt_id = D0_in0_r_ack_tgt_id;
	
	assign A0_out0_r_ack_txn_id = D0_in0_r_ack_txn_id;
	
	assign A0_in0_w_req_vld = S1_out0_w_req_vld;
	
	assign A0_in0_w_req_head = S1_out0_w_req_head;
	
	assign A0_in0_w_req_ail = S1_out0_w_req_tail;
	
	assign A0_in0_w_req_pld = S1_out0_w_req_pld;
	
	assign A0_in0_w_req_src_id = S1_out0_w_req_src_id;
	
	assign A0_in0_w_req_gt_id = S1_out0_w_req_tgt_id;
	
	assign A0_in0_w_req_xn_id = S1_out0_w_req_txn_id;
	
	assign A0_in1_w_req_vld = S2_out0_w_req_vld;
	
	assign A0_in1_w_req_head = S2_out0_w_req_head;
	
	assign A0_in1_w_req_ail = S2_out0_w_req_tail;
	
	assign A0_in1_w_req_pld = S2_out0_w_req_pld;
	
	assign A0_in1_w_req_src_id = S2_out0_w_req_src_id;
	
	assign A0_in1_w_req_gt_id = S2_out0_w_req_tgt_id;
	
	assign A0_in1_w_req_xn_id = S2_out0_w_req_txn_id;
	
	assign A0_in0_r_req_vld = S1_out0_r_req_vld;
	
	assign A0_in0_r_req_head = S1_out0_r_req_head;
	
	assign A0_in0_r_req_ail = S1_out0_r_req_tail;
	
	assign A0_in0_r_req_pld = S1_out0_r_req_pld;
	
	assign A0_in0_r_req_src_id = S1_out0_r_req_src_id;
	
	assign A0_in0_r_req_gt_id = S1_out0_r_req_tgt_id;
	
	assign A0_in0_r_req_xn_id = S1_out0_r_req_txn_id;
	
	assign A0_in1_r_req_vld = S2_out0_r_req_vld;
	
	assign A0_in1_r_req_head = S2_out0_r_req_head;
	
	assign A0_in1_r_req_ail = S2_out0_r_req_tail;
	
	assign A0_in1_r_req_pld = S2_out0_r_req_pld;
	
	assign A0_in1_r_req_src_id = S2_out0_r_req_src_id;
	
	assign A0_in1_r_req_gt_id = S2_out0_r_req_tgt_id;
	
	assign A0_in1_r_req_xn_id = S2_out0_r_req_txn_id;
	
	assign A0_in0_w_ack_rdy = S1_out0_w_ack_rdy;
	
	assign A0_in1_w_ack_rdy = S2_out0_w_ack_rdy;
	
	assign A0_in0_r_ack_dy = S1_out0_r_ack_rdy;
	
	assign A0_in1_r_ack_dy = S2_out0_r_ack_rdy;
	
	assign D0_clk = clk;
	
	assign D0_rst_n = rst_n;
	
	assign D0_in0_w_req_vld = A0_out0_w_req_vld;
	
	assign D0_in0_w_req_head = A0_out0_w_req_head;
	
	assign D0_in0_w_req_tail = A0_out0_w_req_tail;
	
	assign D0_in0_w_req_pld = A0_out0_w_req_pld;
	
	assign D0_in0_w_req_src_id = A0_out0_w_req_src_id;
	
	assign D0_in0_w_req_tgt_id = A0_out0_w_req_tgt_id;
	
	assign D0_in0_w_req_txn_id = A0_out0_w_req_txn_id;
	
	assign D0_in0_r_req_vld = A0_out0_r_req_vld;
	
	assign D0_in0_r_req_head = A0_out0_r_req_head;
	
	assign D0_in0_r_req_tail = A0_out0_r_req_tail;
	
	assign D0_in0_r_req_pld = A0_out0_r_req_pld;
	
	assign D0_in0_r_req_src_id = A0_out0_r_req_src_id;
	
	assign D0_in0_r_req_tgt_id = A0_out0_r_req_tgt_id;
	
	assign D0_in0_r_req_txn_id = A0_out0_r_req_txn_id;
	
	assign D0_in0_w_ack_rdy = A0_out0_w_ack_rdy;
	
	assign D0_in0_r_ack_rdy = A0_out0_r_ack_rdy;
	
	assign D0_out0_w_req_dy = M1_in0_w_req_rdy;
	
	assign D0_out1_w_req_dy = M2_in0_w_req_rdy;
	
	assign D0_out0_r_req_dy = M1_in0_r_req_rdy;
	
	assign D0_out1_r_req_dy = M2_in0_r_req_rdy;
	
	assign D0_out0_w_ack_vld = M1_in0_w_ack_vld;
	
	assign D0_out0_w_ack_head = M1_in0_w_ack_head;
	
	assign D0_out0_w_ack_tail = M1_in0_w_ack_tail;
	
	assign D0_out0_w_ack_pld = M1_in0_w_ack_pld;
	
	assign D0_out0_w_ack_src_id = M1_in0_w_ack_src_id;
	
	assign D0_out0_w_ack_tgt_id = M1_in0_w_ack_tgt_id;
	
	assign D0_out0_w_ack_txn_id = M1_in0_w_ack_txn_id;
	
	assign D0_out1_w_ack_vld = M2_in0_w_ack_vld;
	
	assign D0_out1_w_ack_head = M2_in0_w_ack_head;
	
	assign D0_out1_w_ack_tail = M2_in0_w_ack_tail;
	
	assign D0_out1_w_ack_pld = M2_in0_w_ack_pld;
	
	assign D0_out1_w_ack_src_id = M2_in0_w_ack_src_id;
	
	assign D0_out1_w_ack_tgt_id = M2_in0_w_ack_tgt_id;
	
	assign D0_out1_w_ack_txn_id = M2_in0_w_ack_txn_id;
	
	assign D0_out0_r_ack_vld = M1_in0_r_ack_vld;
	
	assign D0_out0_r_ack_head = M1_in0_r_ack_head;
	
	assign D0_out0_r_ack_tail = M1_in0_r_ack_tail;
	
	assign D0_out0_r_ack_pld = M1_in0_r_ack_pld;
	
	assign D0_out0_r_ack_src_id = M1_in0_r_ack_src_id;
	
	assign D0_out0_r_ack_tgt_id = M1_in0_r_ack_tgt_id;
	
	assign D0_out0_r_ack_txn_id = M1_in0_r_ack_txn_id;
	
	assign D0_out1_r_ack_vld = M2_in0_r_ack_vld;
	
	assign D0_out1_r_ack_head = M2_in0_r_ack_head;
	
	assign D0_out1_r_ack_tail = M2_in0_r_ack_tail;
	
	assign D0_out1_r_ack_pld = M2_in0_r_ack_pld;
	
	assign D0_out1_r_ack_src_id = M2_in0_r_ack_src_id;
	
	assign D0_out1_r_ack_tgt_id = M2_in0_r_ack_tgt_id;
	
	assign D0_out1_r_ack_txn_id = M2_in0_r_ack_txn_id;
	
	assign M1_clk = clk;
	
	assign M1_rst_n = rst_n;
	
	assign M1_in0_r_req_vld = D0_out0_r_req_vld;
	
	assign M1_in0_r_req_head = D0_out0_r_req_head;
	
	assign M1_in0_r_req_tail = D0_out0_r_req_tail;
	
	assign M1_in0_r_req_pld = D0_out0_r_req_pld;
	
	assign M1_in0_r_req_src_id = D0_out0_r_req_src_id;
	
	assign M1_in0_r_req_tgt_id = D0_out0_r_req_tgt_id;
	
	assign M1_in0_r_req_txn_id = D0_out0_r_req_txn_id;
	
	assign M1_in0_w_req_vld = D0_out0_w_req_vld;
	
	assign M1_in0_w_req_head = D0_out0_w_req_head;
	
	assign M1_in0_w_req_tail = D0_out0_w_req_tail;
	
	assign M1_in0_w_req_pld = D0_out0_w_req_pld;
	
	assign M1_in0_w_req_src_id = D0_out0_w_req_src_id;
	
	assign M1_in0_w_req_tgt_id = D0_out0_w_req_tgt_id;
	
	assign M1_in0_w_req_txn_id = D0_out0_w_req_txn_id;
	
	assign M1_in0_r_ack_rdy = D0_out0_r_ack_dy;
	
	assign M1_in0_w_ack_rdy = D0_out0_w_ack_rdy;
	
	assign M1_out0_aw_rdy = D_M1_out0_aw_rdy;
	
	assign M1_out0_w_rdy = D_M1_out0_w_rdy;
	
	assign M1_out0_b_vld = D_M1_out0_b_vld;
	
	assign M1_out0_b_id = D_M1_out0_b_id;
	
	assign M1_out0_b_resp = D_M1_out0_b_resp;
	
	assign M1_out0_ar_rdy = D_M1_out0_ar_rdy;
	
	assign M1_out0_r_vld = D_M1_out0_r_vld;
	
	assign M1_out0_r_id = D_M1_out0_r_id;
	
	assign M1_out0_r_data = D_M1_out0_r_data;
	
	assign M1_out0_r_resp = D_M1_out0_r_resp;
	
	assign M1_out0_r_last = D_M1_out0_r_last;
	
	assign M2_clk = clk;
	
	assign M2_rst_n = rst_n;
	
	assign M2_in0_r_req_vld = D0_out1_r_req_vld;
	
	assign M2_in0_r_req_head = D0_out1_r_req_head;
	
	assign M2_in0_r_req_tail = D0_out1_r_req_tail;
	
	assign M2_in0_r_req_pld = D0_out1_r_req_pld;
	
	assign M2_in0_r_req_src_id = D0_out1_r_req_src_id;
	
	assign M2_in0_r_req_tgt_id = D0_out1_r_req_tgt_id;
	
	assign M2_in0_r_req_txn_id = D0_out1_r_req_txn_id;
	
	assign M2_in0_w_req_vld = D0_out1_w_req_vld;
	
	assign M2_in0_w_req_head = D0_out1_w_req_head;
	
	assign M2_in0_w_req_tail = D0_out1_w_req_tail;
	
	assign M2_in0_w_req_pld = D0_out1_w_req_pld;
	
	assign M2_in0_w_req_src_id = D0_out1_w_req_src_id;
	
	assign M2_in0_w_req_tgt_id = D0_out1_w_req_tgt_id;
	
	assign M2_in0_w_req_txn_id = D0_out1_w_req_txn_id;
	
	assign M2_in0_r_ack_rdy = D0_out1_r_ack_dy;
	
	assign M2_in0_w_ack_rdy = D0_out1_w_ack_rdy;
	
	assign M2_out0_aw_rdy = D_M2_out0_aw_rdy;
	
	assign M2_out0_w_rdy = D_M2_out0_w_rdy;
	
	assign M2_out0_b_vld = D_M2_out0_b_vld;
	
	assign M2_out0_b_id = D_M2_out0_b_id;
	
	assign M2_out0_b_resp = D_M2_out0_b_resp;
	
	assign M2_out0_ar_rdy = D_M2_out0_ar_rdy;
	
	assign M2_out0_r_vld = D_M2_out0_r_vld;
	
	assign M2_out0_r_id = D_M2_out0_r_id;
	
	assign M2_out0_r_data = D_M2_out0_r_data;
	
	assign M2_out0_r_resp = D_M2_out0_r_resp;
	
	assign M2_out0_r_last = D_M2_out0_r_last;
	
	DSlvAxi_node_S1 S1 (
		.clk(S1_clk),
		.rst_n(S1_rst_n),
		.out0_r_req_vld(S1_out0_r_req_vld),
		.out0_r_req_rdy(S1_out0_r_req_rdy),
		.out0_r_req_head(S1_out0_r_req_head),
		.out0_r_req_tail(S1_out0_r_req_tail),
		.out0_r_req_pld(S1_out0_r_req_pld),
		.out0_r_req_src_id(S1_out0_r_req_src_id),
		.out0_r_req_tgt_id(S1_out0_r_req_tgt_id),
		.out0_r_req_txn_id(S1_out0_r_req_txn_id),
		.out0_w_req_vld(S1_out0_w_req_vld),
		.out0_w_req_rdy(S1_out0_w_req_rdy),
		.out0_w_req_head(S1_out0_w_req_head),
		.out0_w_req_tail(S1_out0_w_req_tail),
		.out0_w_req_pld(S1_out0_w_req_pld),
		.out0_w_req_src_id(S1_out0_w_req_src_id),
		.out0_w_req_tgt_id(S1_out0_w_req_tgt_id),
		.out0_w_req_txn_id(S1_out0_w_req_txn_id),
		.out0_r_ack_vld(S1_out0_r_ack_vld),
		.out0_r_ack_rdy(S1_out0_r_ack_rdy),
		.out0_r_ack_head(S1_out0_r_ack_head),
		.out0_r_ack_tail(S1_out0_r_ack_tail),
		.out0_r_ack_pld(S1_out0_r_ack_pld),
		.out0_r_ack_src_id(S1_out0_r_ack_src_id),
		.out0_r_ack_tgt_id(S1_out0_r_ack_tgt_id),
		.out0_r_ack_txn_id(S1_out0_r_ack_txn_id),
		.out0_w_ack_vld(S1_out0_w_ack_vld),
		.out0_w_ack_rdy(S1_out0_w_ack_rdy),
		.out0_w_ack_head(S1_out0_w_ack_head),
		.out0_w_ack_tail(S1_out0_w_ack_tail),
		.out0_w_ack_pld(S1_out0_w_ack_pld),
		.out0_w_ack_src_id(S1_out0_w_ack_src_id),
		.out0_w_ack_tgt_id(S1_out0_w_ack_tgt_id),
		.out0_w_ack_txn_id(S1_out0_w_ack_txn_id),
		.in0_aw_vld(S1_in0_aw_vld),
		.in0_aw_rdy(S1_in0_aw_rdy),
		.in0_aw_addr(S1_in0_aw_addr),
		.in0_aw_id(S1_in0_aw_id),
		.in0_aw_user(S1_in0_aw_user),
		.in0_w_vld(S1_in0_w_vld),
		.in0_w_rdy(S1_in0_w_rdy),
		.in0_w_last(S1_in0_w_last),
		.in0_w_data(S1_in0_w_data),
		.in0_w_strb(S1_in0_w_strb),
		.in0_w_user(S1_in0_w_user),
		.in0_b_vld(S1_in0_b_vld),
		.in0_b_rdy(S1_in0_b_rdy),
		.in0_b_id(S1_in0_b_id),
		.in0_b_resp(S1_in0_b_resp),
		.in0_ar_vld(S1_in0_ar_vld),
		.in0_ar_rdy(S1_in0_ar_rdy),
		.in0_ar_addr(S1_in0_ar_addr),
		.in0_ar_id(S1_in0_ar_id),
		.in0_ar_user(S1_in0_ar_user),
		.in0_r_vld(S1_in0_r_vld),
		.in0_r_rdy(S1_in0_r_rdy),
		.in0_r_id(S1_in0_r_id),
		.in0_r_data(S1_in0_r_data),
		.in0_r_resp(S1_in0_r_resp),
		.in0_r_last(S1_in0_r_last));
	DSlvAxi_node_S2 S2 (
		.clk(S2_clk),
		.rst_n(S2_rst_n),
		.out0_r_req_vld(S2_out0_r_req_vld),
		.out0_r_req_rdy(S2_out0_r_req_rdy),
		.out0_r_req_head(S2_out0_r_req_head),
		.out0_r_req_tail(S2_out0_r_req_tail),
		.out0_r_req_pld(S2_out0_r_req_pld),
		.out0_r_req_src_id(S2_out0_r_req_src_id),
		.out0_r_req_tgt_id(S2_out0_r_req_tgt_id),
		.out0_r_req_txn_id(S2_out0_r_req_txn_id),
		.out0_w_req_vld(S2_out0_w_req_vld),
		.out0_w_req_rdy(S2_out0_w_req_rdy),
		.out0_w_req_head(S2_out0_w_req_head),
		.out0_w_req_tail(S2_out0_w_req_tail),
		.out0_w_req_pld(S2_out0_w_req_pld),
		.out0_w_req_src_id(S2_out0_w_req_src_id),
		.out0_w_req_tgt_id(S2_out0_w_req_tgt_id),
		.out0_w_req_txn_id(S2_out0_w_req_txn_id),
		.out0_r_ack_vld(S2_out0_r_ack_vld),
		.out0_r_ack_rdy(S2_out0_r_ack_rdy),
		.out0_r_ack_head(S2_out0_r_ack_head),
		.out0_r_ack_tail(S2_out0_r_ack_tail),
		.out0_r_ack_pld(S2_out0_r_ack_pld),
		.out0_r_ack_src_id(S2_out0_r_ack_src_id),
		.out0_r_ack_tgt_id(S2_out0_r_ack_tgt_id),
		.out0_r_ack_txn_id(S2_out0_r_ack_txn_id),
		.out0_w_ack_vld(S2_out0_w_ack_vld),
		.out0_w_ack_rdy(S2_out0_w_ack_rdy),
		.out0_w_ack_head(S2_out0_w_ack_head),
		.out0_w_ack_tail(S2_out0_w_ack_tail),
		.out0_w_ack_pld(S2_out0_w_ack_pld),
		.out0_w_ack_src_id(S2_out0_w_ack_src_id),
		.out0_w_ack_tgt_id(S2_out0_w_ack_tgt_id),
		.out0_w_ack_txn_id(S2_out0_w_ack_txn_id),
		.in0_aw_vld(S2_in0_aw_vld),
		.in0_aw_rdy(S2_in0_aw_rdy),
		.in0_aw_addr(S2_in0_aw_addr),
		.in0_aw_id(S2_in0_aw_id),
		.in0_aw_user(S2_in0_aw_user),
		.in0_w_vld(S2_in0_w_vld),
		.in0_w_rdy(S2_in0_w_rdy),
		.in0_w_last(S2_in0_w_last),
		.in0_w_data(S2_in0_w_data),
		.in0_w_strb(S2_in0_w_strb),
		.in0_w_user(S2_in0_w_user),
		.in0_b_vld(S2_in0_b_vld),
		.in0_b_rdy(S2_in0_b_rdy),
		.in0_b_id(S2_in0_b_id),
		.in0_b_resp(S2_in0_b_resp),
		.in0_ar_vld(S2_in0_ar_vld),
		.in0_ar_rdy(S2_in0_ar_rdy),
		.in0_ar_addr(S2_in0_ar_addr),
		.in0_ar_id(S2_in0_ar_id),
		.in0_ar_user(S2_in0_ar_user),
		.in0_r_vld(S2_in0_r_vld),
		.in0_r_rdy(S2_in0_r_rdy),
		.in0_r_id(S2_in0_r_id),
		.in0_r_data(S2_in0_r_data),
		.in0_r_resp(S2_in0_r_resp),
		.in0_r_last(S2_in0_r_last));
	DArbDual_node_A0 A0 (
		.clk(A0_clk),
		.rst_n(A0_rst_n),
		.out0_w_req_vld(A0_out0_w_req_vld),
		.out0_w_req_rdy(A0_out0_w_req_rdy),
		.out0_w_req_head(A0_out0_w_req_head),
		.out0_w_req_tail(A0_out0_w_req_tail),
		.out0_w_req_pld(A0_out0_w_req_pld),
		.out0_w_req_src_id(A0_out0_w_req_src_id),
		.out0_w_req_tgt_id(A0_out0_w_req_tgt_id),
		.out0_w_req_txn_id(A0_out0_w_req_txn_id),
		.out0_r_req_vld(A0_out0_r_req_vld),
		.out0_r_req_rdy(A0_out0_r_req_rdy),
		.out0_r_req_head(A0_out0_r_req_head),
		.out0_r_req_tail(A0_out0_r_req_tail),
		.out0_r_req_pld(A0_out0_r_req_pld),
		.out0_r_req_src_id(A0_out0_r_req_src_id),
		.out0_r_req_tgt_id(A0_out0_r_req_tgt_id),
		.out0_r_req_txn_id(A0_out0_r_req_txn_id),
		.out0_w_ack_vld(A0_out0_w_ack_vld),
		.out0_w_ack_rdy(A0_out0_w_ack_rdy),
		.out0_w_ack_head(A0_out0_w_ack_head),
		.out0_w_ack_tail(A0_out0_w_ack_tail),
		.out0_w_ack_pld(A0_out0_w_ack_pld),
		.out0_w_ack_src_id(A0_out0_w_ack_src_id),
		.out0_w_ack_tgt_id(A0_out0_w_ack_tgt_id),
		.out0_w_ack_txn_id(A0_out0_w_ack_txn_id),
		.out0_r_ack_vld(A0_out0_r_ack_vld),
		.out0_r_ack_rdy(A0_out0_r_ack_rdy),
		.out0_r_ack_head(A0_out0_r_ack_head),
		.out0_r_ack_tail(A0_out0_r_ack_tail),
		.out0_r_ack_pld(A0_out0_r_ack_pld),
		.out0_r_ack_src_id(A0_out0_r_ack_src_id),
		.out0_r_ack_tgt_id(A0_out0_r_ack_tgt_id),
		.out0_r_ack_txn_id(A0_out0_r_ack_txn_id),
		.in0_w_req_vld(A0_in0_w_req_vld),
		.in0_w_req_dy(A0_in0_w_req_dy),
		.in0_w_req_head(A0_in0_w_req_head),
		.in0_w_req_ail(A0_in0_w_req_ail),
		.in0_w_req_pld(A0_in0_w_req_pld),
		.in0_w_req_src_id(A0_in0_w_req_src_id),
		.in0_w_req_gt_id(A0_in0_w_req_gt_id),
		.in0_w_req_xn_id(A0_in0_w_req_xn_id),
		.in1_w_req_vld(A0_in1_w_req_vld),
		.in1_w_req_dy(A0_in1_w_req_dy),
		.in1_w_req_head(A0_in1_w_req_head),
		.in1_w_req_ail(A0_in1_w_req_ail),
		.in1_w_req_pld(A0_in1_w_req_pld),
		.in1_w_req_src_id(A0_in1_w_req_src_id),
		.in1_w_req_gt_id(A0_in1_w_req_gt_id),
		.in1_w_req_xn_id(A0_in1_w_req_xn_id),
		.in0_r_req_vld(A0_in0_r_req_vld),
		.in0_r_req_dy(A0_in0_r_req_dy),
		.in0_r_req_head(A0_in0_r_req_head),
		.in0_r_req_ail(A0_in0_r_req_ail),
		.in0_r_req_pld(A0_in0_r_req_pld),
		.in0_r_req_src_id(A0_in0_r_req_src_id),
		.in0_r_req_gt_id(A0_in0_r_req_gt_id),
		.in0_r_req_xn_id(A0_in0_r_req_xn_id),
		.in1_r_req_vld(A0_in1_r_req_vld),
		.in1_r_req_dy(A0_in1_r_req_dy),
		.in1_r_req_head(A0_in1_r_req_head),
		.in1_r_req_ail(A0_in1_r_req_ail),
		.in1_r_req_pld(A0_in1_r_req_pld),
		.in1_r_req_src_id(A0_in1_r_req_src_id),
		.in1_r_req_gt_id(A0_in1_r_req_gt_id),
		.in1_r_req_xn_id(A0_in1_r_req_xn_id),
		.in0_w_ack_vld(A0_in0_w_ack_vld),
		.in0_w_ack_rdy(A0_in0_w_ack_rdy),
		.in0_w_ack_head(A0_in0_w_ack_head),
		.in0_w_ack_il(A0_in0_w_ack_il),
		.in0_w_ack_pld(A0_in0_w_ack_pld),
		.in0_w_ack_src_id(A0_in0_w_ack_src_id),
		.in0_w_ack_gt_id(A0_in0_w_ack_gt_id),
		.in0_w_ack_xn_id(A0_in0_w_ack_xn_id),
		.in1_w_ack_vld(A0_in1_w_ack_vld),
		.in1_w_ack_rdy(A0_in1_w_ack_rdy),
		.in1_w_ack_head(A0_in1_w_ack_head),
		.in1_w_ack_il(A0_in1_w_ack_il),
		.in1_w_ack_pld(A0_in1_w_ack_pld),
		.in1_w_ack_src_id(A0_in1_w_ack_src_id),
		.in1_w_ack_gt_id(A0_in1_w_ack_gt_id),
		.in1_w_ack_xn_id(A0_in1_w_ack_xn_id),
		.in0_r_ack_vld(A0_in0_r_ack_vld),
		.in0_r_ack_dy(A0_in0_r_ack_dy),
		.in0_r_ack_head(A0_in0_r_ack_head),
		.in0_r_ack_il(A0_in0_r_ack_il),
		.in0_r_ack_pld(A0_in0_r_ack_pld),
		.in0_r_ack_src_id(A0_in0_r_ack_src_id),
		.in0_r_ack_gt_id(A0_in0_r_ack_gt_id),
		.in0_r_ack_xn_id(A0_in0_r_ack_xn_id),
		.in1_r_ack_vld(A0_in1_r_ack_vld),
		.in1_r_ack_dy(A0_in1_r_ack_dy),
		.in1_r_ack_head(A0_in1_r_ack_head),
		.in1_r_ack_il(A0_in1_r_ack_il),
		.in1_r_ack_pld(A0_in1_r_ack_pld),
		.in1_r_ack_src_id(A0_in1_r_ack_src_id),
		.in1_r_ack_gt_id(A0_in1_r_ack_gt_id),
		.in1_r_ack_xn_id(A0_in1_r_ack_xn_id));
	DDecDual_node_D0 D0 (
		.clk(D0_clk),
		.rst_n(D0_rst_n),
		.in0_w_req_vld(D0_in0_w_req_vld),
		.in0_w_req_rdy(D0_in0_w_req_rdy),
		.in0_w_req_head(D0_in0_w_req_head),
		.in0_w_req_tail(D0_in0_w_req_tail),
		.in0_w_req_pld(D0_in0_w_req_pld),
		.in0_w_req_src_id(D0_in0_w_req_src_id),
		.in0_w_req_tgt_id(D0_in0_w_req_tgt_id),
		.in0_w_req_txn_id(D0_in0_w_req_txn_id),
		.in0_r_req_vld(D0_in0_r_req_vld),
		.in0_r_req_rdy(D0_in0_r_req_rdy),
		.in0_r_req_head(D0_in0_r_req_head),
		.in0_r_req_tail(D0_in0_r_req_tail),
		.in0_r_req_pld(D0_in0_r_req_pld),
		.in0_r_req_src_id(D0_in0_r_req_src_id),
		.in0_r_req_tgt_id(D0_in0_r_req_tgt_id),
		.in0_r_req_txn_id(D0_in0_r_req_txn_id),
		.in0_w_ack_vld(D0_in0_w_ack_vld),
		.in0_w_ack_rdy(D0_in0_w_ack_rdy),
		.in0_w_ack_head(D0_in0_w_ack_head),
		.in0_w_ack_tail(D0_in0_w_ack_tail),
		.in0_w_ack_pld(D0_in0_w_ack_pld),
		.in0_w_ack_src_id(D0_in0_w_ack_src_id),
		.in0_w_ack_tgt_id(D0_in0_w_ack_tgt_id),
		.in0_w_ack_txn_id(D0_in0_w_ack_txn_id),
		.in0_r_ack_vld(D0_in0_r_ack_vld),
		.in0_r_ack_rdy(D0_in0_r_ack_rdy),
		.in0_r_ack_head(D0_in0_r_ack_head),
		.in0_r_ack_tail(D0_in0_r_ack_tail),
		.in0_r_ack_pld(D0_in0_r_ack_pld),
		.in0_r_ack_src_id(D0_in0_r_ack_src_id),
		.in0_r_ack_tgt_id(D0_in0_r_ack_tgt_id),
		.in0_r_ack_txn_id(D0_in0_r_ack_txn_id),
		.out0_w_req_vld(D0_out0_w_req_vld),
		.out0_w_req_dy(D0_out0_w_req_dy),
		.out0_w_req_head(D0_out0_w_req_head),
		.out0_w_req_tail(D0_out0_w_req_tail),
		.out0_w_req_pld(D0_out0_w_req_pld),
		.out0_w_req_src_id(D0_out0_w_req_src_id),
		.out0_w_req_tgt_id(D0_out0_w_req_tgt_id),
		.out0_w_req_txn_id(D0_out0_w_req_txn_id),
		.out1_w_req_vld(D0_out1_w_req_vld),
		.out1_w_req_dy(D0_out1_w_req_dy),
		.out1_w_req_head(D0_out1_w_req_head),
		.out1_w_req_tail(D0_out1_w_req_tail),
		.out1_w_req_pld(D0_out1_w_req_pld),
		.out1_w_req_src_id(D0_out1_w_req_src_id),
		.out1_w_req_tgt_id(D0_out1_w_req_tgt_id),
		.out1_w_req_txn_id(D0_out1_w_req_txn_id),
		.out0_r_req_vld(D0_out0_r_req_vld),
		.out0_r_req_dy(D0_out0_r_req_dy),
		.out0_r_req_head(D0_out0_r_req_head),
		.out0_r_req_tail(D0_out0_r_req_tail),
		.out0_r_req_pld(D0_out0_r_req_pld),
		.out0_r_req_src_id(D0_out0_r_req_src_id),
		.out0_r_req_tgt_id(D0_out0_r_req_tgt_id),
		.out0_r_req_txn_id(D0_out0_r_req_txn_id),
		.out1_r_req_vld(D0_out1_r_req_vld),
		.out1_r_req_dy(D0_out1_r_req_dy),
		.out1_r_req_head(D0_out1_r_req_head),
		.out1_r_req_tail(D0_out1_r_req_tail),
		.out1_r_req_pld(D0_out1_r_req_pld),
		.out1_r_req_src_id(D0_out1_r_req_src_id),
		.out1_r_req_tgt_id(D0_out1_r_req_tgt_id),
		.out1_r_req_txn_id(D0_out1_r_req_txn_id),
		.out0_w_ack_vld(D0_out0_w_ack_vld),
		.out0_w_ack_rdy(D0_out0_w_ack_rdy),
		.out0_w_ack_head(D0_out0_w_ack_head),
		.out0_w_ack_tail(D0_out0_w_ack_tail),
		.out0_w_ack_pld(D0_out0_w_ack_pld),
		.out0_w_ack_src_id(D0_out0_w_ack_src_id),
		.out0_w_ack_tgt_id(D0_out0_w_ack_tgt_id),
		.out0_w_ack_txn_id(D0_out0_w_ack_txn_id),
		.out1_w_ack_vld(D0_out1_w_ack_vld),
		.out1_w_ack_rdy(D0_out1_w_ack_rdy),
		.out1_w_ack_head(D0_out1_w_ack_head),
		.out1_w_ack_tail(D0_out1_w_ack_tail),
		.out1_w_ack_pld(D0_out1_w_ack_pld),
		.out1_w_ack_src_id(D0_out1_w_ack_src_id),
		.out1_w_ack_tgt_id(D0_out1_w_ack_tgt_id),
		.out1_w_ack_txn_id(D0_out1_w_ack_txn_id),
		.out0_r_ack_vld(D0_out0_r_ack_vld),
		.out0_r_ack_dy(D0_out0_r_ack_dy),
		.out0_r_ack_head(D0_out0_r_ack_head),
		.out0_r_ack_tail(D0_out0_r_ack_tail),
		.out0_r_ack_pld(D0_out0_r_ack_pld),
		.out0_r_ack_src_id(D0_out0_r_ack_src_id),
		.out0_r_ack_tgt_id(D0_out0_r_ack_tgt_id),
		.out0_r_ack_txn_id(D0_out0_r_ack_txn_id),
		.out1_r_ack_vld(D0_out1_r_ack_vld),
		.out1_r_ack_dy(D0_out1_r_ack_dy),
		.out1_r_ack_head(D0_out1_r_ack_head),
		.out1_r_ack_tail(D0_out1_r_ack_tail),
		.out1_r_ack_pld(D0_out1_r_ack_pld),
		.out1_r_ack_src_id(D0_out1_r_ack_src_id),
		.out1_r_ack_tgt_id(D0_out1_r_ack_tgt_id),
		.out1_r_ack_txn_id(D0_out1_r_ack_txn_id));
	DMstAxi_node_M1 M1 (
		.clk(M1_clk),
		.rst_n(M1_rst_n),
		.in0_r_req_vld(M1_in0_r_req_vld),
		.in0_r_req_rdy(M1_in0_r_req_rdy),
		.in0_r_req_head(M1_in0_r_req_head),
		.in0_r_req_tail(M1_in0_r_req_tail),
		.in0_r_req_pld(M1_in0_r_req_pld),
		.in0_r_req_src_id(M1_in0_r_req_src_id),
		.in0_r_req_tgt_id(M1_in0_r_req_tgt_id),
		.in0_r_req_txn_id(M1_in0_r_req_txn_id),
		.in0_w_req_vld(M1_in0_w_req_vld),
		.in0_w_req_rdy(M1_in0_w_req_rdy),
		.in0_w_req_head(M1_in0_w_req_head),
		.in0_w_req_tail(M1_in0_w_req_tail),
		.in0_w_req_pld(M1_in0_w_req_pld),
		.in0_w_req_src_id(M1_in0_w_req_src_id),
		.in0_w_req_tgt_id(M1_in0_w_req_tgt_id),
		.in0_w_req_txn_id(M1_in0_w_req_txn_id),
		.in0_r_ack_vld(M1_in0_r_ack_vld),
		.in0_r_ack_rdy(M1_in0_r_ack_rdy),
		.in0_r_ack_head(M1_in0_r_ack_head),
		.in0_r_ack_tail(M1_in0_r_ack_tail),
		.in0_r_ack_pld(M1_in0_r_ack_pld),
		.in0_r_ack_src_id(M1_in0_r_ack_src_id),
		.in0_r_ack_tgt_id(M1_in0_r_ack_tgt_id),
		.in0_r_ack_txn_id(M1_in0_r_ack_txn_id),
		.in0_w_ack_vld(M1_in0_w_ack_vld),
		.in0_w_ack_rdy(M1_in0_w_ack_rdy),
		.in0_w_ack_head(M1_in0_w_ack_head),
		.in0_w_ack_tail(M1_in0_w_ack_tail),
		.in0_w_ack_pld(M1_in0_w_ack_pld),
		.in0_w_ack_src_id(M1_in0_w_ack_src_id),
		.in0_w_ack_tgt_id(M1_in0_w_ack_tgt_id),
		.in0_w_ack_txn_id(M1_in0_w_ack_txn_id),
		.out0_aw_vld(M1_out0_aw_vld),
		.out0_aw_rdy(M1_out0_aw_rdy),
		.out0_aw_addr(M1_out0_aw_addr),
		.out0_aw_id(M1_out0_aw_id),
		.out0_aw_user(M1_out0_aw_user),
		.out0_w_vld(M1_out0_w_vld),
		.out0_w_rdy(M1_out0_w_rdy),
		.out0_w_last(M1_out0_w_last),
		.out0_w_data(M1_out0_w_data),
		.out0_w_strb(M1_out0_w_strb),
		.out0_w_user(M1_out0_w_user),
		.out0_b_vld(M1_out0_b_vld),
		.out0_b_rdy(M1_out0_b_rdy),
		.out0_b_id(M1_out0_b_id),
		.out0_b_resp(M1_out0_b_resp),
		.out0_ar_vld(M1_out0_ar_vld),
		.out0_ar_rdy(M1_out0_ar_rdy),
		.out0_ar_addr(M1_out0_ar_addr),
		.out0_ar_id(M1_out0_ar_id),
		.out0_ar_user(M1_out0_ar_user),
		.out0_r_vld(M1_out0_r_vld),
		.out0_r_rdy(M1_out0_r_rdy),
		.out0_r_id(M1_out0_r_id),
		.out0_r_data(M1_out0_r_data),
		.out0_r_resp(M1_out0_r_resp),
		.out0_r_last(M1_out0_r_last));
	DMstAxi_node_M2 M2 (
		.clk(M2_clk),
		.rst_n(M2_rst_n),
		.in0_r_req_vld(M2_in0_r_req_vld),
		.in0_r_req_rdy(M2_in0_r_req_rdy),
		.in0_r_req_head(M2_in0_r_req_head),
		.in0_r_req_tail(M2_in0_r_req_tail),
		.in0_r_req_pld(M2_in0_r_req_pld),
		.in0_r_req_src_id(M2_in0_r_req_src_id),
		.in0_r_req_tgt_id(M2_in0_r_req_tgt_id),
		.in0_r_req_txn_id(M2_in0_r_req_txn_id),
		.in0_w_req_vld(M2_in0_w_req_vld),
		.in0_w_req_rdy(M2_in0_w_req_rdy),
		.in0_w_req_head(M2_in0_w_req_head),
		.in0_w_req_tail(M2_in0_w_req_tail),
		.in0_w_req_pld(M2_in0_w_req_pld),
		.in0_w_req_src_id(M2_in0_w_req_src_id),
		.in0_w_req_tgt_id(M2_in0_w_req_tgt_id),
		.in0_w_req_txn_id(M2_in0_w_req_txn_id),
		.in0_r_ack_vld(M2_in0_r_ack_vld),
		.in0_r_ack_rdy(M2_in0_r_ack_rdy),
		.in0_r_ack_head(M2_in0_r_ack_head),
		.in0_r_ack_tail(M2_in0_r_ack_tail),
		.in0_r_ack_pld(M2_in0_r_ack_pld),
		.in0_r_ack_src_id(M2_in0_r_ack_src_id),
		.in0_r_ack_tgt_id(M2_in0_r_ack_tgt_id),
		.in0_r_ack_txn_id(M2_in0_r_ack_txn_id),
		.in0_w_ack_vld(M2_in0_w_ack_vld),
		.in0_w_ack_rdy(M2_in0_w_ack_rdy),
		.in0_w_ack_head(M2_in0_w_ack_head),
		.in0_w_ack_tail(M2_in0_w_ack_tail),
		.in0_w_ack_pld(M2_in0_w_ack_pld),
		.in0_w_ack_src_id(M2_in0_w_ack_src_id),
		.in0_w_ack_tgt_id(M2_in0_w_ack_tgt_id),
		.in0_w_ack_txn_id(M2_in0_w_ack_txn_id),
		.out0_aw_vld(M2_out0_aw_vld),
		.out0_aw_rdy(M2_out0_aw_rdy),
		.out0_aw_addr(M2_out0_aw_addr),
		.out0_aw_id(M2_out0_aw_id),
		.out0_aw_user(M2_out0_aw_user),
		.out0_w_vld(M2_out0_w_vld),
		.out0_w_rdy(M2_out0_w_rdy),
		.out0_w_last(M2_out0_w_last),
		.out0_w_data(M2_out0_w_data),
		.out0_w_strb(M2_out0_w_strb),
		.out0_w_user(M2_out0_w_user),
		.out0_b_vld(M2_out0_b_vld),
		.out0_b_rdy(M2_out0_b_rdy),
		.out0_b_id(M2_out0_b_id),
		.out0_b_resp(M2_out0_b_resp),
		.out0_ar_vld(M2_out0_ar_vld),
		.out0_ar_rdy(M2_out0_ar_rdy),
		.out0_ar_addr(M2_out0_ar_addr),
		.out0_ar_id(M2_out0_ar_id),
		.out0_ar_user(M2_out0_ar_user),
		.out0_r_vld(M2_out0_r_vld),
		.out0_r_rdy(M2_out0_r_rdy),
		.out0_r_id(M2_out0_r_id),
		.out0_r_data(M2_out0_r_data),
		.out0_r_resp(M2_out0_r_resp),
		.out0_r_last(M2_out0_r_last));

endmodule
//[UHDL]Content End [md5:ae592e51cf1222e6cafc52f45ad6165a]

//[UHDL]Parameter Start [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]Parameter End [md5:d41d8cd98f00b204e9800998ecf8427e]

